### ISSUE TITLE
Using kitty terminal

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#115]
Quick question.

I am trying to use kitty by doing this in my config:

```lua
external_term = "kitty"
```

The thing is this opening an external terminal (i.e., another terminal outside nvim, instead of a new window within nvim). Is this expected behavior? Can I use kitty within neovim?

**Comment by PMassicotte** [comment]
Also, then I use `external_term = "kitty"` I  am getting this message:

![image](https://github.com/R-nvim/R.nvim/assets/4519221/de74223b-eb9b-406a-902d-57b885972aae)

**Comment by jalvesaq** [comment]
The goal is to have separate windows, which can be freely positioned, for example, on different monitors (if you have a dual monitor setup), or partially overlapping each other (if you have only one small monitor).

You can't use `kitty` within `nvim` because `kitty` is a graphical application, not a text one.

You can suppress the warning with the following config option:

```lua
silent_term = true
```

**Comment by PMassicotte** [comment]
Thank you for the explanation!

**Comment by samtrek** [comment]
I am using kitty and I can share my kitty config if you want. Although I am not using an external term but it is possible. I view data tables in a separate tab witthin kitty although I could also view it in a new window if I so desire

**Comment by samtrek** [comment]
I mostly run kitty as a server, and use only one instance of kitty, from this instance, I can then launch new tabs, split the tabs and so on. I have something like this in my sway config

set $term kitty -1 --instance-group "kitty_sock" -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock

And then have something like this for viewing datatables

vim.g["R_csv_app"] = "kitten @ --to unix:/tmp/kitty_sock launch --type tab sc-im" 
so I believe that the above can be modified as an external_app to something like this
vim.g["R_external_app"] = "kitten @ --to unix:/tmp/kitty_sock launch --type window"

their are many options that can be considered, you can use tab, window, split the current window and so on, you can get more info from 

https://sw.kovidgoyal.net/kitty/remote-control/#remote-control-via-a-socket

**Comment by PMassicotte** [comment]
> vim.g["R_external_app"] = "kitten @ --to unix:/tmp/kitty_sock launch --type window"

do you mean `external_term`?

**Comment by samtrek** [comment]
> > vim.g["R_external_app"] = "kitten @ --to unix:/tmp/kitty_sock launch --type window"
> 
> do you mean `external_term`?

Yes it should have been
vim.g["R_external_term"]

**Comment by PMassicotte** [comment]
Should I define `set $term kitty -1 --instance-group "kitty_sock" -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock` in my `zshrc` file?

**Comment by samtrek** [comment]
The $term is mainly defined in sway I don't know the window manager you are using mine is sway it has similar configs to i3, in gnome, KDE and other none tilled window manager I have no clue, and then subsequently the $term is called when a kitty terminal is to be launched.

**Comment by PMassicotte** [comment]
Cool this is almost working out. The only thing is that the terminal is opening horizontally instead of vertically on the right as before.

**Comment by samtrek** [comment]
Did you split your kitty terminal, by creating windows within it?, if yes, you may have to change the default r.nvim layout configs by reducing the length at which it changes to horizontal layout.

**Comment by PMassicotte** [comment]
I have tried 

`kitten @ --to unix:/tmp/kitty_sock launch --type window --location=after`
`kitten @ --to unix:/tmp/kitty_sock launch --type window --location=vsplit`
`kitten @ --to unix:/tmp/kitty_sock launch --type window --location=hsplit`

**Comment by samtrek** [comment]
seems kitty has a default layout scheme, below is lifted from the kitty page which can be changed with ctrl+shift+l

https://sw.kovidgoyal.net/kitty/overview/

	By default, all layouts are enabled and you can switch between layouts using the [ctrl+shift+l](https://						sw.kovidgoyal.net/	kitty/conf/#shortcut-kitty.Next-layout) key combination. You can also create shortcuts to select particular layouts, and choose which layouts you want to enable, see [Layout management](https://sw.kovidgoyal.net/kitty/conf/#conf-kitty-shortcuts-layout) for examples. The first layout listed in [enabled_layouts](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.enabled_layouts) becomes the default layout.

**Comment by samtrek** [comment]
To make it permanent you can specify the default layout in your `kitty.conf`, because I am not sure if the changes made through `ctrl+shift+L` is permanent or not.

**Comment by samtrek** [comment]
It is possible to set the layout you want, however, you have to include the layout you want when you run the initial server/socket
set $term kitty -1 --instance-group "kitty_sock" -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock `-o enable_layout=splits"`

or include it in your kitty.conf as `layout splits`

you may have to kill all active kitty terminals before the new layout can be used.

then you can then use the following to state either horizontal split or vertical split

`kitten @ --to unix:/tmp/kitty_sock launch --type window --location hsplit`
`kitten @ --to unix:/tmp/kitty_sock launch --type window --location hsplit`

**Comment by jalvesaq** [comment]
"You can change [...] get text from one window and send text to another, etc."

This means that it would be possible to run R in an external terminal (`kitty`) without Tmux.

**Comment by samtrek** [comment]
yes I have done this before without any kind of problem

**Comment by PMassicotte** [comment]
Got it working. I was playing with this because I could not use all the vim motion in the built-in terminal. For example, when I am in normal mode, I can not use `ciw` or other derivative. It gives me:

![image](https://github.com/R-nvim/R.nvim/assets/4519221/8d2a6d46-cea4-4fa0-9185-a711df8bd764)

**Comment by PMassicotte** [comment]
Reviving this older discussion. 

How would you close the terminal (kitty in my case) on `:qa`? If I use `localleader rq` it close the terminal, not it is not working if I quit my _editor_ window.

![image](https://github.com/R-nvim/R.nvim/assets/4519221/72421bf8-26fc-4dc9-8362-7856e3bd7b0d)

I would like to close the terminal automatically when I `:qa`. Possible?

**Comment by jalvesaq** [comment]
There is an option for this: `:h auto_quit`.

**Comment by PMassicotte** [comment]
Excellent! Thank you

**Comment by PMassicotte** [comment]
Just pasting my config here, so it is findable by others (in case someone else needs it):

In my `R.nvim` config I have this:

```lua
external_term = "/usr/bin/kitten @ --to unix:/tmp/kitty_sock launch --type window --location=vsplit",
```

In my i3 config I have this to start kitty and make it listen on a socket:

```
bindsym $mod+Return exec kitty -1 --instance-group "kitty_sock" -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock
```
