### ISSUE TITLE
Open help documentation in a vertical split

### ISSUE THREAD

**Issue by cswingle** [R-nvim/R.nvim#117]
Feature request: I would like help documentation to open in a vertical split, which is something that nvim-r used to do. There are hints that "vertical" is a legal option for the `nvimpager` option (lua/r/edit.lua, line 259), but it's not implemented in doc.lua.

I'll see if I can get it started in an upcoming pull request.

**Comment by jalvesaq** [comment]
I forgot to delete the "vertical" option from the function that opens the example. But we can add the option back, although not in a complicated way as before.
