### ISSUE TITLE
hook defined in the config r.nvim works for only the first opened *.r file

### ISSUE THREAD

**Issue by samtrek** [R-nvim/R.nvim#120]
The hook defined in the r.nvim config file works only for the first opened *.r files (not tested in *.rmd), without closing the first file, other opened *.r files do not respond to the keybinds within the hook.

Anyway to implement it in such a way that the hook applies to all *.r files and possibly *.rmd files?

**Comment by jalvesaq** [comment]
Are you using the new hook `on_filetype`?

**Comment by samtrek** [comment]
the hook defined in my config looks like this, lifted directly form the suggested config, I did not use the `on_filetype`, it only has the `after_config` (I have little knowledge of lua, so I try to keep my config similar to the suggested config). All the other localleader+other keybindings work as they should, just that the config below is very continent and I have gotten used to it. 
 
hook = {
        after_config = function()
          -- This function will be called at the FileType event
          -- of files supported by R.nvim. This is an
          -- opportunity to create mappings local to buffers.
          if vim.o.syntax ~= "rbrowser" then
            vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "<Plug>RDSendLine", {})
            vim.api.nvim_buf_set_keymap(0, "v", "<Enter>", "<Plug>RSendSelection", {})
          end
          -- Pipe operator
          vim.api.nvim_buf_set_keymap(0, "i", "<C-S-m>", " |>", {})
        end,
      },

**Comment by jalvesaq** [comment]
I forgot to update the README. But I will change the example to:

```lua
hook = {
  on_filetype = function ()
    -- This function will be called at the FileType event
    -- of files supported by R.nvim. This is an
    -- opportunity to create mappings local to buffers.
    vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "<Plug>RDSendLine", {})
    vim.api.nvim_buf_set_keymap(0, "v", "<Enter>", "<Plug>RSendSelection", {})
  end
},
```
