### ISSUE TITLE
Closing inline code chunks with backticks

### ISSUE THREAD

**Issue by j-w-e** [R-nvim/R.nvim#121]
In an Rmd or qmd file, you can start an inline code block with a backtick using the `rmdchunk=2` option. Can I request that typing a second backtick closes the chunk, not closes and opens a new one?

For example, typing a `` ` `` when starting from this (with cursor represented by `|`):
````
Test `r |`
````

Currently, that results in:
````
Test `r ``r |`
````

I would propose that this is more intuitive, and matches how autopair plugins tend to work, for example:
````
Test `r `|
````

I assume this can be achieved by checking if the next character is a `` ` ``, as an additional `if` statement following [this line](https://github.com/R-nvim/R.nvim/blob/35e17323568afe3d42ed571960244e230549b697/lua/r/rmd.lua#L65), but I don't know enough of the Neovim API to know how to do that sensibly.

**Comment by jalvesaq** [comment]
> I would propose that this is more intuitive, and matches how autopair plugins tend to work

I agree. I'll see this later.
