### ISSUE TITLE
`RDSendParagraph` or `RDSendLine` error when using `radian` as R app?

### ISSUE THREAD

**Issue by mingsu** [R-nvim/R.nvim#125]
I can use <Plug>RDSendLine to correctly send content to R console when the R code contains lines end with ",", for example:

```r
  require(ggplot2)
  data.frame(x = 1, y = 2) |>
    ggplot(aes(x = x,
      y = y)) +
  geom_point()
```

Above codes gives error like: 

```
r$> require(ggplot2)

r$> data.frame(x = 1, y = 2) |>
        ggplot(aes(x = x,))

r$>       y = y)) +
Error: unexpected ')' in "      y = y)"

r$>   geom_point()
geom_point: na.rm = FALSE
stat_identity: na.rm = FALSE
position_identity 

r$>
```

But below codes works

```r
  require(ggplot2)
  data.frame(x = 1, y = 2) |>
    ggplot(aes(x = x, y = y)) +
  geom_point()
```

I think this is resulted by the `radian` autocomplete the bracket, would it be possible to fix this?

**Comment by PMassicotte** [comment]
I just tried your code, and it is working on my side. I am not sure what is going on. Maybe @jalvesaq can reproduce it?

**Comment by jalvesaq** [comment]
It works on my side if using R. I can replicate the bug with Radian as `R_app`, but the bug disappears with the option:

```lua
bracketed_paste = true,
```

**Comment by jalvesaq** [comment]
If `bracketed_paste` is required also on macOS and Windows when using radian, we can make its default value `true` if `R_app` includes the "radian" string.

**Comment by mingsu** [comment]
Sounds great, thank you very much.
