### ISSUE TITLE
nvimcom error executing command: slotNames

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#128]
I am facing a `nvimcom` error when executing this set of commands:

```r
library(rphylopic)

uuid <- get_uuid(name = "Fistulifera solaris", n = 1)
img <- get_phylopic(uuid = uuid) 
```

```
nvimcom error executing command: slotNames(img@content[[1]]@c
ontent[[103]]@d@segments[[17]])
Error in img@content[[1]]@content[[103]]@d@segments[[18]] : 
  subscript out of bounds
```

It works fine in R/radian, but crashes within nvim.

Any ideas?

**Comment by jalvesaq** [comment]
Trying to replicate the issue:

```
> img <- get_phylopic(uuid = uuid)
Error in value[[3L]](cond) : 
  Problem downloading vector file. Please try again.
```

**Comment by PMassicotte** [comment]
Interesting,

![image](https://github.com/R-nvim/R.nvim/assets/4519221/898cb03b-6267-4060-ad28-aa74ae7e179f)

**Comment by PMassicotte** [comment]
Maybe the service was down when you tried?

**Comment by jalvesaq** [comment]
I'm still getting the same result. Printing `uuid` I get "ad77846b-1071-4800-9e7b-eae4675fcecb".

**Comment by PMassicotte** [comment]
humm weird, let me try to find out what is going on.

**Comment by PMassicotte** [comment]
I have the same result as you, the crash is when I execute ` get_phylopic(uuid = uuid) `

**Comment by jalvesaq** [comment]
Finally, this bug is fixed on the branch https://github.com/jalvesaq/R.nvim/commits/unnamed_list/
I plan to merge it tomorrow.

**Comment by PMassicotte** [comment]
Thank you very much!

**Comment by jalvesaq** [comment]
A simpler code to replicate the bug:

```r
x <- list(1, "a", 1, "a")
```

After sending the line above to R, do `\ro` and `\r=`. The forth element will be color highlighted as `numeric`.

**Comment by PMassicotte** [comment]
This is what I have.

![image](https://github.com/R-nvim/R.nvim/assets/4519221/5c55613f-23d3-4257-8ece-afaa8dfe01a0)

**Comment by jalvesaq** [comment]
This is the bug. But on the `unnamed_list` branch, `[[4]]` should have the same color as `[[2]]`.

**Comment by PMassicotte** [comment]
> This is the bug. But on the `unnamed_list` branch, `[[4]]` should have the same color as `[[2]]`.

I confirm, fixed on my side.
