### ISSUE TITLE
Suggestions for configuring init.lua file?

### ISSUE THREAD

**Issue by VtheRtech** [R-nvim/R.nvim#136]
Hello!

I recently jumped over from nvim-r to r.nvim after reading the documentation and realizing r.nvim had better compatibility with neovim.  I'm using [lazyvim](https://github.com/LazyVim/LazyVim) as my configuration, I'm wondering if I configured r.nvim correctly I followed the guidance from the wiki and place the code lua code block in the init.lua file. 

However, I'm wondering if this was the best way to handle this with my current configuration, intuitively I would think adding a r.nvim.lua file in plugin folder with the code block in it, then adding ``require("plugins.r.nvim")`` to `init.lua` might be a better option. I linked my current config below. 

[init.lua file](https://github.com/VtheRtech/Vim-Config-Files/blob/main/init.lua)

I also tried configuring autocompletion for parathesis but for some reason, it doesn't seem to work.

If you can give me some pointers or suggestions it would be greatly appreciated!

**Comment by jalvesaq** [comment]
When you say "autocompletion for parenthesis", do you mean auto-pair completion? [nvim-autopairs](https://github.com/windwp/nvim-autopairs) works for me.

If you mean R code completion triggered by an opening parenthesis, this works automatically with [cmp-r](https://github.com/R-nvim/cmp-r).

I use `lazy.nvim`, but not `LazyVim`, so I can't comment on it.

**Comment by VtheRtech** [comment]
> When you say "autocompletion for parenthesis", do you mean auto-pair completion? [nvim-autopairs](https://github.com/windwp/nvim-autopairs) works for me.
> 
> If you mean R code completion triggered by an opening parenthesis, this works automatically with [cmp-r](https://github.com/R-nvim/cmp-r).
> 
> I use `lazy.nvim`, but not `LazyVim`, so I can't comment on it.

Thanks! I considered your suggestions and spent the day re-organizing my config files.
