### ISSUE TITLE
R.nvim struggles to find parsers

### ISSUE THREAD

**Issue by akthe-at** [R-nvim/R.nvim#139]
` Warn   notify.warn R.nvim R.nvim requires treesitter parsers for "r", "markdown" and "rnoweb". Please, install them.`
warning is encountered when opening r files on windows. Issue appears to stem from posix paths that look for the parsers. PR solving the issue should be up momentarily.

**Comment by PMassicotte** [comment]
Does using `//` on Windows could solve the problem? In that case, we could only use `//` for both Linux and Windows? Just asking, have not used Windows for ages. :)

**Comment by PMassicotte** [comment]
Then it sounds good to me! Thank you for this, will let @jalvesaq have a look to merge it.

**Comment by jalvesaq** [comment]
It works on Linux! I'll merge it.
