### ISSUE TITLE
Can't send code from R documentation to R Console

### ISSUE THREAD

**Issue by jalvesaq** [R-nvim/R.nvim#143]
How to replicate the bug:

1. Start R: `<LocalLeader>rf`
2. Put the cursor over a word, e.g. `rnorm`, and press `<LocalLeader>rh`.
3. Go to the _Examples_ section: `<LocalLeader>ge`
4. Try to send any code to R.

The error is:

```
[...] There is no parser available for buffer [...]
```

Maybe we have to create a parser for `rdoc`: https://tree-sitter.github.io/tree-sitter/creating-parsers

Workaround: instead of `<LocalLeader>rh`, press `<LocalLeader>re` to open the _Examples_ section in a temporary R file.

**Comment by PMassicotte** [comment]
I usually do what you suggest as work around. Also, once the help file is open, I can to `:set filetype=r` and send code directly from the examples section.
