### ISSUE TITLE
setting object browser and console verticallly

### ISSUE THREAD

**Issue by ConYel** [R-nvim/R.nvim#148]
Hello and thank you very much for the updated version of Nvim-R/Rnvim!
I just moved to the R.nvim and I'm trying to figure out how to make the console and the obj browser spawn right of the editor window while being being in horizontal split between them.
Something like that ->
           | console
Editor | console
           | obj browser

Thank you in advance!

**Comment by jalvesaq** [comment]
Choose an editor width that leaves enough room for the R console to be on the right. Then, put the Object Browser below the R Console. Depending on your screen width, this might work:

```lua
  min_editor_width = 81,
  objbr_place = "console,below",
```

**Comment by ConYel** [comment]
Great thank you very much!!!
