### ISSUE TITLE
Setting pipe_keymap not working

### ISSUE THREAD

**Issue by joihci** [R-nvim/R.nvim#151]
I'm trying to change the keybind for inserting the pipe operator `|>`.

I'm not sure I understand the documentation correctly as per _6.5. Assignment pipe operators_ but I set `pipe_keybind` as a global variable. If I open a .R file with nvim and run `:let g:` I can see the variable correctly set. However it has no effect on the behaviour of the pipe keybind. Setting it to `""` does not unbind the default `<space>,` (space is set as leader) keybind and setting it to `"<M-,>"` as is my intention does not work.

Is this a bug or am I doing something wrong?

Info:
- Neovim version v0.10.0
- Using vim-plug plugin manager, all plugins up to date
- Ubuntu 22.04.04
- tmux 3.2a

Any more info I should provide about my setup?

**Comment by jalvesaq** [comment]
As usual with Lua plugins, `R.nvim` is not configured by global variables. You have to create a Lua table with your options and pass it to `require("r").setup()`. Please, see the examples in the [README](https://github.com/R-nvim/R.nvim/blob/main/README.md), and the [Wiki](https://github.com/R-nvim/R.nvim/wiki/Configuration).

**Comment by joihci** [comment]
Great, thanks!

Solved with `lua require("r").setup({ pipe_keymap = "<M-,>" })` in `init.vim`
