### ISSUE TITLE
Upcoming R version might break nvimcom

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#167]
https://github.com/dgkf/debugadapter/pull/16#issuecomment-2201163387

@jalvesaq do you have an idea?

**Comment by PMassicotte** [comment]
If this can be fixed, we are going to have a functional DAP inside neovim for R!

**Comment by jalvesaq** [comment]
We can manually build `nvimcom` in a terminal emulator because the function `Rf_removeTaskCallbackByName` is still declared in `include/R_ext/Callbacks.h`, but it is not available at run time and, consequently, when loading `nvimcom`, we get the error:

```
undefined symbol: Rf_removeTaskCallbackByName
```

**Comment by PMassicotte** [comment]
This is a bit out of my expertise. What does it mean exactly? Does it mean that there is a discrepancy between declaration and availability of some kind of function?

**Comment by jalvesaq** [comment]
Yes, it's a bug in R-devel. Probably, they removed the function on purpose but forgot to remove its declaration from the corresponding header file. We can report the bug and, then, they will either bring the function back or remove the declaration. Although no longer available in C, the function is still available in the R language. I will see if we can use it from R (not C).

**Comment by jalvesaq** [comment]
I moved the C code to R at the branch https://github.com/R-nvim/R.nvim/tree/R_task

**Comment by PMassicotte** [comment]
wow you are fast (wish I had your skills!)

So far so good, I am using it. Let me try to configure dap.
