### ISSUE TITLE
In tmux RDSendLine does not work when opening a second buffer

### ISSUE THREAD

**Issue by statquant** [R-nvim/R.nvim#181]
Hello,
using tmux everything works as expected on the file I opened first but if I decide to start another buffer I cannot send any line, however rest of features seems to be working <mapleader>rq, <mapleader>rh.
Is this something I can change ?

**Comment by jalvesaq** [comment]
I can't replicate the issue. It works here. Could you be more specific, please? What is the value of `external_term`? How did you start another buffer? What is the file type of each buffer? Can you note any key binding conflict between `:nmap` and `:RMapsDesc`?

**Comment by statquant** [comment]
That’s great news, I’ll come back tomorrow with details and edit this message. Thanks for the prompt answer

**Comment by jalvesaq** [comment]
Thanks for the feedback!
