### ISSUE TITLE
Running R in a ToggleTerm

### ISSUE THREAD

**Issue by lucasvoirin** [R-nvim/R.nvim#184]
Thanks for this great plugin!

I'd like to know if it's possible to run R in a ToggleTerm from akinsho/toggleterm.nvim instead of the default nvim terminal?

**Comment by jalvesaq** [comment]
I don't have ToggleTerm installed, but you can try to run R in it and check if the functionality that depends on R being running works, such as `<LocalLeader>rh` and `<LocalLeader>ro`. Please, report your results.

**Comment by lucasvoirin** [comment]
It seems that R.nvim does not detect R when it is run in a ToggleTerm. Functionalities like `<LocalLeader>rh` and `<LocalLeader>ro` indicate that R is not running (with messages like `Did you start R?` and `The Object Browser can be opened only if R is running.`). Maybe because ToggleTerm is opened by a specific `:ToggleTerm` command ( and not by `:term`)?

**Comment by jalvesaq** [comment]
If you look at the function `r.run.start_R2()` you will see that it saves a file to be sourced by R on startup before calling the function `r.term.start_term()`. So, to run R in a ToggleTerm or any non-supported terminal emulator, it will be necessary to override at least some of the functions from the Lua module `r.term`. I'm sorry, but I'm not going to do this. If you convince us of the advantages of ToggleTerm, we could make `R.nvim` dependent on ToggleTerm, but others might prefer other plugins to manage Neovim's built-in terminal emulator...

My personal preference is to avoid dependencies as much as possible.

**Comment by lucasvoirin** [comment]
No problem, I completely understand! Thank you for your quick response!
