### ISSUE TITLE
renv is ignored when using external_term

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#188]
I just noticed that `renv` is not loaded if I am using `external_term`:

```lua
external_term = "/usr/bin/kitten @ --to unix:/tmp/kitty_sock launch --type window --location=vsplit --keep-focus",
```

```r
R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Platform: x86_64-pc-linux-gnu (64-bit)
```

If I comment out to use the built-in terminal, and reopen the project, it is all good, R is loaded and takes into account the `renv` project:

```r
Project '~/Desktop/test' loaded. [renv 1.0.7]
R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Platform: x86_64-pc-linux-gnu (64-bit)
```

Do you experience the same thing with `tmux`?

**Comment by jalvesaq** [comment]
Tmux requires that environment variables be set explicitly. It's not enough to have them set in Neovim. Does `renv` require any environment variable that was set in Neovim?

**Comment by PMassicotte** [comment]
Not that I am aware of. R starts and should look for a `.Rprofile` in the root directory, which contains

```r
source("renv/activate.R")
```

This will activate R with `renv`. 

If I type `getwd()` I see that the R session is correctly inside my root directory. If I start `radian` manually (outside nvim) it also works.

**Comment by jalvesaq** [comment]
I'm sorry, but I have no other idea. This was the main problem that I found when starting to use Tmux to run R in an external terminal.

**Comment by PMassicotte** [comment]
This has something to do with this `i3` config:

```
bindsym $mod+Return exec kitty -1 --instance-group "kitty_sock" -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock --directory=xxx
```

`xxx` is the directory where `kitty` initially launch. The default is `.` (home dir, https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-directory).

The funny thing is that if I set this to `--directory='~/Desktop/test1'`, then R starts with `renv` (whatever the directory I start nvim). If I open another project, let's say `test2` which also uses `renv`, R will load `test1` project, but in the console, if I type `getwd()`, it will show that I am inside `test2`, although `renv` for `test1` is loaded.

I will try to find a solution and report back so we can document it.

**Comment by jalvesaq** [comment]
We have an option that might be relevant in this case: `setwd`. Perhaps, `R.nvim` is changing the working directory _after_ `renv` has already started in the wrong directory...

**Comment by PMassicotte** [comment]
I found it! I set `--cwd=current` :

```lua
external_term = "/usr/bin/kitten @ --to unix:/tmp/kitty_sock launch --type window --location=vsplit --keep-focus --cwd=current",
```

https://sw.kovidgoyal.net/kitty/conf/#window-management

**Comment by PMassicotte** [comment]
Maybe we should document this.

**Comment by jalvesaq** [comment]
Yes, I think this is the kind of information that fits well in the Wiki.

**Comment by PMassicotte** [comment]
First draft for `kitty`:

https://github.com/R-nvim/R.nvim/wiki/External-Terminals
