### ISSUE TITLE
Rpipe sends keymap string instead of pipe operator `|>`

### ISSUE THREAD

**Issue by joihci** [R-nvim/R.nvim#195]
When the cursor is placed directly after a symbol and the following line contains a comment the Rpipe keymap does not send the pipe operator `|>` but the actual keymap for the pipe operator which in my case is `<M-,>`.

I'm testing with a minimal `init.vim`, nvim version 0.10.0, ubuntu version 22.04.4.

Behaviour demonstrated in video

[Rpipe_bug_out.webm](https://github.com/user-attachments/assets/fbb577e3-86d1-4b2c-8405-4bb5f61eb7c1)

**Comment by jalvesaq** [comment]
Maybe this bug is the same #190 which I can't replicate.

**Comment by jalvesaq** [comment]
@joihci, what are your Neovim version and operating system? Could you show how `R.nvim` and `nvim-treesitter` is configured in your system?

**Comment by PMassicotte** [comment]
If you want to try different versions of `nvim`: https://github.com/MordechaiHadad/bob

**Comment by joihci** [comment]
@jalvesaq
Neovim:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```
OS:
```
Ubuntu 22.04.4 LTS
Linux 6.5.0-41-generic x86_64
```
The minimal init.vim I used for the screencapture above:
```lua
call plug#begin(stdpath("data")."/plugged")
"Plug 'R-nvim/R.nvim', { 'branch': 'fix-send-function-treesitter-r' }
Plug 'R-nvim/R.nvim'
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
call plug#end()

lua require("r").setup({ pipe_keymap = "<M-,>" })
let mapleader="\<Space>"
let maplocalleader="\<Space>"
lua <<EOF
require("nvim-treesitter.configs").setup {
  ensure_installed = "all", -- one of "all",
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  playground = {
    enable = true,
    disable = {},
    updatetime = 25,
    persist_queries = false,
    keybindings = {
      toggle_query_editor = "o",
      toggle_hl_groups = "i",
      toggle_injected_languages = "t",
      toggle_anonymous_nodes = "a",
      toggle_language_display = "I",
      focus_language = "f",
      unfocus_language = "F",
      update = "R",
      goto_node = "<cr>",
      show_help = "?",
    },
  }
}
EOF

```

**Comment by jalvesaq** [comment]
I'll try your minimal `init.vim`. Anyway, these two lines should be at the top of your `init.vim`:

```vim
let mapleader="\<Space>"
let maplocalleader="\<Space>"
```

These are the first three lines of my `init.lua`:

```lua
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.keymap.set('',  '<Space>', '<Nop>')
```

**Comment by jalvesaq** [comment]
You could also try to begin with this: https://github.com/R-nvim/R.nvim/wiki/Configuration#minimal-configuration

And, then, add your other plugins one at a time.

**Comment by joihci** [comment]
Update: I made no changes on my end but updated the `R.nvim` plugin since yesterday and now the strange behavior is gone. I have no idea what changed in the last commits that fixed the issue...

Here is my update history for the `R.nvim` repo. As you can see I updated yesterday at 13:39 and again today at 13:15.
```
f4b79a1 (HEAD -> main, origin/main, origin/HEAD) HEAD@{2024-07-23 13:15:05 +0000}: merge origin/main: Fast-forward
ae256d9 HEAD@{2024-07-23 13:15:05 +0000}: checkout: moving from main to main
ae256d9 HEAD@{2024-07-22 13:39:37 +0000}: merge origin/main: Fast-forward
6286b6b HEAD@{2024-07-22 13:39:37 +0000}: checkout: moving from fix-send-function-treesitter-r to main
```

**Comment by jalvesaq** [comment]
Thanks for the feedback!
