### ISSUE TITLE
Syntax highlighting is not enabled in the help window

### ISSUE THREAD

**Issue by gssfaw** [R-nvim/R.nvim#200]
I've recently noticed that syntax highlighting in the help window is not enabled when I press <ll>rh. I can turn it on with the command `:TSEnable highlight`.
Here is the minimal `init.lua` file: 
<details>
  <summary>init.lua</summary>

```lua
vim.g.mapleader = [[\]]
vim.g.maplocalleader = [[,]]
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    {
        {
            "R-nvim/R.nvim",
            lazy = false
        },
        {
            "nvim-treesitter/nvim-treesitter",
            run = ":TSUpdate",
            config = function()
                require("nvim-treesitter.configs").setup({
                    ensure_installed = { "markdown", "markdown_inline", "r", "rnoweb", "yaml" },
                })
            end
        },
        "R-nvim/cmp-r",
        {
            "hrsh7th/nvim-cmp",
            config = function()
                require("cmp").setup({ sources = { { name = "cmp_r" } } })
                require("cmp_r").setup({})
            end,
        },
    } }
)
```
</details>

`nvim --version
NVIM v0.10.1`

https://github.com/user-attachments/assets/595a9b27-d43c-4ce7-9e51-6e188c25a2e5

**Comment by jalvesaq** [comment]
I have this in `nvim-treesitter` config:

```lua
return
    {
        "nvim-treesitter/nvim-treesitter",
        run = ":TSUpdate",
        config = function ()
            require("nvim-treesitter.configs").setup({
                sync_install = true,
                --- ... other options
                highlight = {
                    enable = true,
                },
                --- ... other options
            })
        end,
    },
```

**Comment by gssfaw** [comment]
@jalvesaq I've included it in the minimal config, but the problem persists. I did a git bisect and it looks like the problem was introduced with the commit 1d2e6c303b2bde089e18b0d7cc5e56b79332cc5e . I don't really know why it happens, but changing the `"filetype"` back to `"syntax"` in line https://github.com/R-nvim/R.nvim/blob/6bbd927ce8c799e9de087a2c28a6b7d869fc2e4e/lua/r/rdoc.lua#L18 fixes the issue

**Comment by PMassicotte** [comment]
I am not sure what is going on, but it is working on my side

https://asciinema.org/a/MMB0wtnuXAFVGnKrP6MJubtsl

**Comment by gssfaw** [comment]
I am so sorry, I forgot that the ftplugin is still loaded with a different init file. And I had some silly mistake in my rmd ftplugin file. Removing it solves the problem. Previously, because I wanted to get some features working for the latex code block, I was calling vimtex from the rmd ftplugin.
