### ISSUE TITLE
Better capture nodes for printing the object under the cursor

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#201]
I have found that using the print function:

```lua
<Cmd>lua require('r.run').action('print')
```

It was capturing extra element when used within a function. For example, if I have my cursor on `land` this will be the result:

![image](https://github.com/user-attachments/assets/126dac1c-9250-4fde-8f57-fdda0eddd58a)

I believe we could use `treesitter` to better capture what we want with that simple expression:

```s
argument: (argument 
  value: (identifier) @capture) 
```
Which, for this particular code, is capturing all the identifier and could be used to only send the relevant object to the console.

![image](https://github.com/user-attachments/assets/155eb422-96c2-4115-a6f2-cf2beb6dda03)

**Comment by PMassicotte** [comment]
I think this is capturing all possible cases

```
argument: (argument 
  value: (identifier) @capture) 

(program 
 (identifier) @capture2) 

(binary_operator
  lhs: (identifier) @capture3) 
```

**Comment by jalvesaq** [comment]
Very interesting! I'll be able to look at this only on Friday because I'm
travelling without my laptop.

**Comment by jalvesaq** [comment]
I couldn't see the screenshot well on my mobile phone...

Please, do `<LocalLeader>rp` with the cursor over the two `summary` functions below:

```r
a <- rnorm(100)
b <- rnorm(100)
m <- lm(a ~ b)
summary(a)
summary(m)
```

You will see that different functions are printed on the R Console because the first objects are different (`a` = "numeric", and `m` = "lm").

That is, the extra argument sent to `nvim.print()` is useful sometimes.

**Comment by PMassicotte** [comment]
This is not the issue.

Check the right-hand side of the first screenshot. It sends two things, `land` and `geom_spatraster`.

**Comment by PMassicotte** [comment]
ah ok, sending this extra line is on purpose to add extra context when using the same keyword?

**Comment by jalvesaq** [comment]
> ah ok, sending this extra line is on purpose to add extra context when using the same keyword?

Yes, the second argument passed to `nvim.print()` helps choose the correct print method. If the previous lines of code were already sent to R, `nvimcom` will get the class of the first object passed as an argument and check if there is a method specific to that class. The same procedure is used by `cmp-r` during completion.

**Comment by PMassicotte** [comment]
That makes sense. Closing this.
