### ISSUE TITLE
Server crashes when trying to use `spData` package

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#211]
See the attached GIF:

![Peek 2024-08-13 09-04](https://github.com/user-attachments/assets/b1c79411-cace-45d8-b699-fd5071cbc3f8)

Results of `:messages`:

```
[Server] Number of separators: 0 (order^F(^Ffunctionp^R)                                                            
"Server" exited with status 139                                                                                     
Press ENTER or type command to continue 
```

**Comment by PMassicotte** [comment]
Good catch. Easy fix, or do we ignore this as this is not a common situation? Have not tried, but can this cause the same kind of issue reading a CSV file with line break in column names?

**Comment by jalvesaq** [comment]
Perhaps, it can cause a problem with CSV, and it's probably easy to fix. But I can't look at it now. I'll see it later today.

**Comment by jalvesaq** [comment]
I uploaded a new branch (`c_bugs`) where I'm trying to fix bugs in the `rnvimserver`, but I couldn't fix this issue yet. I located a line with an invalid reading but didn't get it right yet.
