### ISSUE TITLE
Issue with data.table and In-Place Assignment

### ISSUE THREAD

**Issue by caeu** [R-nvim/R.nvim#216]
Issue with data.table and In-Place Assignment

Description

When using the data.table package in R.nvim, sending code that involves the in-place assignment operator `:=` or its equivalent `let()` causes the data.table object to be printed to the R console. This issue occurs only when the number of lines exceeds the `max_paste_lines` limit (default: 20). This behavior is not observed in the standard R console or RStudio. Although minor, it can clutter the console, especially when there are multiple in-place operations or dealing large tables of many columns.

Steps to Reproduce

1) Execute a block of code with data.table in-place assignment (:=) where the number of lines exceeds `max_paste_lines`. It can be empty lines, comments, or any code.
2) Observe that the data.table object is unexpectedly printed to the console.

Additional Issue (Separate Report May Follow)

There’s another issue involving data.table that results in a loss of connection with R.nvim. I haven’t been able to reliably reproduce this yet, as it only occurs with specific data I’m working with. Valgrind didn't work for me on CentOS 7 or two MacBooks (Intel and ARM). I will file a separate issue once I have more details, but I mention it here as it might be related. This issue involves normal assignment where a large data.table is filtered using `unique()` and assigned back to the same variable name.

![output](https://github.com/user-attachments/assets/1386ef40-0a6c-4d98-889c-5587f9fdf62a)

**Comment by jalvesaq** [comment]
Did you try this in the `R.nvim` config?

```lua
   source_args = "print.eval = FALSE"
```

**Comment by caeu** [comment]
Now I did, it solved both issues. So happy, and a bit embarrassed for missing it in the docs.
