### ISSUE TITLE
<Plug>RDSendLine and <Plug>RSendselection send "Rnvim.source()" and "Rnvim.selection()" to R console

### ISSUE THREAD

**Issue by Spacecortez** [R-nvim/R.nvim#224]
Hello.
I've run into a curious bug where sending R code to the console fails for a particular function.

The code in question is here:

```
edit_indicators <- function(domain_name) {
  services <- show_indicators(domain_name)
  print(paste0((services |> kable()), "\n"))

  indicators <- readin(prompt = "Enter indicator numbers to edit.\n") |>
    stringr::str_split(" ") |>
    sapply(as.double)

  print("Editing the following indicators:")
  new_services <- (services |> filter(num %in% indicators))
  print(new_services |> kable())

  new_service <- readin(prompt = "Define new service name.\n")
  new_services$service <- new_service

  print("New service definition:")
  rows_update(services, new_services, by = "num") |>
    kable() |>
    print()

  if (readline(prompt = "Confirm changes?") %in% c("y", "yes")) {
    rows_update(indicator_services, new_services, by = c("domain", "num"))
    write_csv(indicator_services, "indicator_services.csv")
    print("Indicators updated!")
  } else {
    print("Exiting.")
  }
}
```

If I put my cursor on the first line and hit Enter (bound to <Plug>RDSendLine), the console just reads "Rnvim.source()", and my cursor jumps to the line after the function.  Similarly if I select the whole function and hit Enter the console just reads "Rnvim.selection()".

However, if I select the text up to and including the lines

```
    kable() |>
    print()
```

and then hit Enter, the selected code is correctly sent to the console, and then I can send the rest of the function by hitting Enter.

But, if I select up to and including those lines and include the white space line after, the R console only receives "Rnvim.selection()".

I can confirm the code works as expected once I get it entered properly into the console.
I'm running my R console from a terminal window in neovim.
Any ideas?

**Comment by Spacecortez** [comment]
I have realized that the code is actually being sent to the R console in the above examples, it's just not visible.  So I guess this is working as intended and I just missed something in the documentation.

**Comment by jalvesaq** [comment]
Please, see the option `source_args`.
