### ISSUE TITLE
Incomplete string received. Expected 600 bytes; received 599. 

### ISSUE THREAD

**Issue by liubianshi** [R-nvim/R.nvim#235]
After typing `getwd(`, a warning pops up "Incomplete string received. Expected 600 bytes; received 599. ".

If change this code:

https://github.com/R-nvim/R.nvim/blob/d58d5d854a6198c53154bbc7cc34c6a83bc83260/lua/r/job.lua#L75

to:

`incomplete_input.received = incomplete_input.received + cmd:len() + 1`

the warning is removed and does not seem to cause any other problems.

**Comment by liubianshi** [comment]
New problems will arise with incorrect complementary entries.

![test](https://github.com/user-attachments/assets/c9c99fc3-3ddf-4ddd-96c5-a777fafa8f71)

**Comment by jalvesaq** [comment]
I can't replicate the issue on Linux (Debian testing) with NVIM v0.11.0-dev-722+g9570ad24f (compiled a few days ago).

**Comment by liubianshi** [comment]
It should be possible to reproduce it in arch linux in a minimal configuration.

OS: Arch Linux x86_64
Kernel: 6.10.10-arch1-1

NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
no `.Rprofile` `.Renviron`

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
  {
    "R-nvim/R.nvim",
    lazy = false
  },
  {
    "nvim-treesitter/nvim-treesitter",
    run = ":TSUpdate",
    config = function ()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "markdown", "markdown_inline", "r", "rnoweb", "yaml" },
        highlight = { enable = true },
      })
    end
  },
  "R-nvim/cmp-r",
  {
    "hrsh7th/nvim-cmp",
    config = function()
      require("cmp").setup({ sources = {{ name = "cmp_r" }}})
      require("cmp_r").setup({ })
    end,
  },
})
```

```bash
nvim /tmp/test.R
```

![test_000](https://github.com/user-attachments/assets/ec192a00-94ab-44ea-88cf-334f892b956a)

**Comment by jalvesaq** [comment]
I'm sorry for the long delay. I was doing something wrong. Now, I finally managed to replicate the bug and it should be fixed on the branch "fix_no_args_compl". Could you try it, please?

**Comment by liubianshi** [comment]
The problem should have been solved.
