### ISSUE TITLE
How can I disable the autocompletion when I type ` in insert mode on an empty line

### ISSUE THREAD

**Issue by weberam2** [R-nvim/R.nvim#242]
I'm writing a paper in a .qmd file

On an empty line, if I type `, it autocompletes to a code chunk.

However, in quarto, I sometimes want to type `r something`

I'm pretty sure the behaviour is coming from [here](https://github.com/R-nvim/R.nvim/blob/e3fc31112fac08f451c06a627d8876ab8ce6a393/lua/r/rmd.lua#L13)

But I am using LazyVim's Extra package, and I'm not sure how to disable this behaviour...

Cheers

**Comment by jalvesaq** [comment]
It seems that you have found the solution: https://github.com/R-nvim/cmp-r/issues/11#issuecomment-2400486530
