### ISSUE TITLE
Feature request: send all chunks sequentially, regardless of language

### ISSUE THREAD

**Issue by andy941** [R-nvim/R.nvim#248]
Would it be possible to have a command like `RSendChunkFH` that works with quarto documents with multiple languages? I use regularly a mixture of python and R with reticulate and it would be very useful, especially if there is also something like `SendAllAboveCells` (not sure if there is something like that already).

Thank you, great plugin! I have tried many setups in Neovim for data science and this is by far the best, really a pleasure to work with especially when coupled with otter.nvim to handle lsps for mutliple languages.

Andrea

**Comment by jalvesaq** [comment]
Could you please try the branch "py_r_ch"? In a rapid test, it works.

**Comment by andy941** [comment]
Amazing:
![image](https://github.com/user-attachments/assets/26a7248b-df3f-4309-95fc-84ef29793aaf)

Works on my machine too in a simple example. I can try something more complex at work tomorrow if you like but seems to work. I was sending all cells in this one, does the plugin define a command to send cells above the current one? I can try that too.

Thank you!

**Comment by PMassicotte** [comment]
> does the plugin define a command to send cells above the current one?

yeah, `cu` I think.

**Comment by jalvesaq** [comment]
> I was sending all cells in this one, does the plugin define a command to send cells above the current one?

I don't remember having it. All commands are shown by `:RMapsDesc`. You can also inspect the file `lua/r/maps.lua`.

**Comment by jalvesaq** [comment]
If nobody found any problem with the branch "py_r_ch", we can merge it...
