### ISSUE TITLE
Not inside R or Python code chunk.

### ISSUE THREAD

**Issue by mknoll** [R-nvim/R.nvim#251]
For .Rmd files, a similar behaviour as described in https://github.com/R-nvim/R.nvim/issues/190 occurs. 
I.e. a new .Rmd file with 
```{r}
a <- 1 *cursor*
```
gives "Not inside R or Python code chunk".
Temporarily, :InspectTree fixes this, but this does not work for long. 

Modifying line 577 of r/send.lua to 

if lang ~= "r" and lang ~= "markdown" then

seems to fix this.

**Comment by jalvesaq** [comment]
I can't replicate the bug with this minimal `rmd` file (3 lines):

````
```{r}
a <- 1
```
````

**Comment by jalvesaq** [comment]
If your `rmd` file has a single line, it's invalid because the code block delimiters are missing.

**Comment by mknoll** [comment]
hi, no the files looks like in our first answer, including the delimiters... 
Seems as if adding markdown to the lang check doesn't help long,  :InspectTree is needed quite often. 
I'm temporarily calling it from send.lua (after each line) which makes everything slow but at least allows the known usage.

NVIM v0.11.0-dev-1022+g8c532a9ea
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
Run ":verbose version" for more info

TS was updated

**Comment by mknoll** [comment]
lazy.nvim
- {lazy.nvim} version 11.14.1
- OK {git} version 2.47.0
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found


nvim-treesitter:                     require("nvim-treesitter.health").check()

Installation
- WARNING tree-sitter executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- WARNING node executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK git executable found.
- OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.2.1 20240910
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.11.5-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000"
}

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - rnoweb              ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓


vim.treesitter:                       require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: markdown             ABI: 14, path: /home/mknoll/.local/share/nvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /home/mknoll/.local/share/nvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: r                    ABI: 14, path: /home/mknoll/.local/share/nvim/lazy/nvim-treesitter/parser/r.so
- OK Parser: rnoweb               ABI: 13, path: /home/mknoll/.local/share/nvim/lazy/nvim-treesitter/parser/rnoweb.so
- OK Parser: yaml                 ABI: 14, path: /home/mknoll/.local/share/nvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: c                    ABI: 14, path: /usr/local/lib/nvim/parser/c.so
- OK Parser: lua                  ABI: 14, path: /usr/local/lib/nvim/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /usr/local/lib/nvim/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /usr/local/lib/nvim/parser/markdown_inline.so
- OK Parser: query                ABI: 14, path: /usr/local/lib/nvim/parser/query.so
- OK Parser: vim                  ABI: 14, path: /usr/local/lib/nvim/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /usr/local/lib/nvim/parser/vimdoc.so
- Can load WASM parsers: false

**Comment by jalvesaq** [comment]
Please, try the minimal config from the README or the wiki. If it works with a minimal config, add back your complete config one piece at a time until you can replicate the bug again.

**Comment by mknoll** [comment]
ok, found the problem:

this was working till the last update, didn't change my init.lua for quite some time:
``
        {
                "nvim-treesitter/nvim-treesitter",
                run = ":TSUpdate",
                config = function ()
                        require("nvim-treesitter.configs").setup({
                                ensure_installed = { "markdown", "markdown_inline", "r", "rnoweb" },
                                highlight = { enable = true },
                        })
                end
        },
``

but now yaml is additionally required - if not installed, will create this strange behavior of non executable bugs. 

``
        {
                "nvim-treesitter/nvim-treesitter",
                run = ":TSUpdate",
                config = function ()
                        require("nvim-treesitter.configs").setup({
                                ensure_installed = { "markdown", "markdown_inline", "r", "rnoweb", "yaml" },
                                highlight = { enable = true },
                        })
                end
        },
``

Thanks for your help :)

**Comment by jalvesaq** [comment]
Thanks for the feedback. I will update the README and wiki. However, after uninstalling the YAML parser, I get this warning message when starting to edit an R file:

```
R.nvim ! WARN R.nvim requires treesitter parsers for "r", "markdown", "rnoweb", and "yaml". Please, install them.
```

I'm surprised that this message didn't appear to you.

**Comment by mknoll** [comment]
You're right - however, this message disappeared after approx. 0.5s when opening an Rmd/R file ;-) So that was obviously too fast for me :) 
Maybe the checkhealth might be another good place for this.
Thanks again

**Comment by jalvesaq** [comment]
The pull request #253 adds the `health.lua` module.
