### ISSUE TITLE
`RDSendLine` and `RSendSelection` error when using radian as the R terminal

### ISSUE THREAD

**Issue by dianchia** [R-nvim/R.nvim#254]
### Operating system
Windows 11 Home Single Language

### Neovim version (nvim -v)
NVIM v0.11.0-dev-958+g45f8f957c

### R version
4.4.1

### Radian version
0.6.13
Installed through pip with `pip install -U radian`

### Configuration
I use LazyVim with `lang.r` extras enabled. The config for R.nvim from LazyVim is as follow:
```lua
{
  "R-nvim/R.nvim",
  lazy = false,
  opts = {
    -- Create a table with the options to be passed to setup()
    R_args = { "--quiet", "--no-save" },
    hook = {
      on_filetype = function()
        -- This function will be called at the FileType event
        -- of files supported by R.nvim. This is an
        -- opportunity to create mappings local to buffers.
        vim.keymap.set("n", "<Enter>", "<Plug>RDSendLine", { buffer = true })
        vim.keymap.set("v", "<Enter>", "<Plug>RSendSelection", { buffer = true })

        local wk = require("which-key")
        wk.add({
          buffer = true,
          { "<localleader>a", group = "all" },
          { "<localleader>b", group = "between marks" },
          { "<localleader>c", group = "chunks" },
          { "<localleader>f", group = "functions" },
          { "<localleader>g", group = "goto" },
          { "<localleader>i", group = "install" },
          { "<localleader>k", group = "knit" },
          { "<localleader>p", group = "paragraph" },
          { "<localleader>q", group = "quarto" },
          { "<localleader>r", group = "r general" },
          { "<localleader>s", group = "split or send" },
          { "<localleader>t", group = "terminal" },
          { "<localleader>v", group = "view" },
        })
      end,
    },
    pdfviewer = "",
  },
  config = function(_, opts)
    vim.g.rout_follow_colorscheme = true
    require("r").setup(opts)
    require("r.pdf.generic").open = vim.ui.open
  end,
}
```
I changed the app used from `R` to `radian` and enabled `bracketed_paste` with the following config:
```lua
return {
    "R-nvim/R.nvim",
    opts = {
        R_app = "radian",
        bracketed_paste = true,
    },
}
```

### Describe the bug
When dealing with code that has `,` at the end of the line, sending it to the radian will cause error. For example:
```r
library(ggplot2)
library(dplyr)

diamonds %>%
    select(carat, price) %>%
    ggplot(aes(x = price, y = carat)) +
    geom_point() +
    labs(
        title = "Carat vs. Price",
        x = "Price",
        y = "Carat"
    )
```
The above code produces the following result.
```r
r$> library(ggplot2)

r$> library(dplyr)

r$>

r$> diamonds %>%                                                          
        select(carat, price) %>%                                          
            ggplot(aes(x = price, y = carat)) +                           
                geom_point() +                                            
                    labs()

r$>         title = "Carat vs. Price",
Error: unexpected ',' in "        title = "Carat vs. Price","

r$>         x = "Price",
Error: unexpected ',' in "        x = "Price","

r$>         y = "Carat"

r$>     )
Error: unexpected ')' in "    )"
```

### Expected behaviour
The code should run without error and produce a plot.

### Steps to reproduce
The following steps assume that LazyVim is used and `lang.r` extras is enabled.
1. Start neovim in a directory
2. Create a new R file with any name
3. Copy and paste the code above to the file
4. Start the R terminal using `<localleader>rf`
5. Send to code to terminal by either using `<localleader>aa` or select the code and press Enter

Sending the whole file to R using `<localleader>aa` sends the code line by line instead of sourcing it as well, so the same problem still exists.
Any help would be greatly appreciated.

**Comment by jalvesaq** [comment]
I can't replicate the bug on Linux.

**Comment by jalvesaq** [comment]
Sorry, you are using `radian`, and I'm not using it. So, I can't guarantee that it works on Linux.

**Comment by PMassicotte** [comment]
I am using radian, I will look at  it when I am back to the office on Monday.

**Comment by PMassicotte** [comment]
Works fine here:

![Peek 2024-10-28 09-57](https://github.com/user-attachments/assets/3db1c9c0-426b-45f7-9f18-970ee2046ec9)

Part of my config

```lua
opts = {
            R_app = "radian",
            R_cmd = "R",
            esc_term = true,
            hl_term = false,
            objbr_place = "console,below",
            objbr_auto_start = false,
            objbr_h = 20,
            auto_start = "always",
            auto_quit = true,
            external_term = "/usr/bin/kitten @ --to unix:/tmp/kitty_sock launch --type window --location=vsplit --keep-focus --cwd=current",
```

**Comment by dianchia** [comment]
> Works fine here:
> 
> ![Peek 2024-10-28 09-57](https://private-user-images.githubusercontent.com/4519221/380744592-3db1c9c0-426b-45f7-9f18-970ee2046ec9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjQ4NzAsIm5iZiI6MTczMDEyNDU3MCwicGF0aCI6Ii80NTE5MjIxLzM4MDc0NDU5Mi0zZGIxYzljMC00MjZiLTQ1ZjctOWYxOC05NzBlZTIwNDZlYzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTQwOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg1NDRkM2NiNzljYTVjNGQzMDE1YzkyNzZjZmMwZWIzYmFkMWE3OWFiNzg3NDZkYzA2YzRlYjY3ZmI1YzFmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.89qyf1XYtC07ue4po2uF_ik6tDsx5j8T99_T6ktpb2k) [ ![Peek 2024-10-28 09-57](https://private-user-images.githubusercontent.com/4519221/380744592-3db1c9c0-426b-45f7-9f18-970ee2046ec9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjQ4NzAsIm5iZiI6MTczMDEyNDU3MCwicGF0aCI6Ii80NTE5MjIxLzM4MDc0NDU5Mi0zZGIxYzljMC00MjZiLTQ1ZjctOWYxOC05NzBlZTIwNDZlYzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTQwOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg1NDRkM2NiNzljYTVjNGQzMDE1YzkyNzZjZmMwZWIzYmFkMWE3OWFiNzg3NDZkYzA2YzRlYjY3ZmI1YzFmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.89qyf1XYtC07ue4po2uF_ik6tDsx5j8T99_T6ktpb2k) ](https://private-user-images.githubusercontent.com/4519221/380744592-3db1c9c0-426b-45f7-9f18-970ee2046ec9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjQ4NzAsIm5iZiI6MTczMDEyNDU3MCwicGF0aCI6Ii80NTE5MjIxLzM4MDc0NDU5Mi0zZGIxYzljMC00MjZiLTQ1ZjctOWYxOC05NzBlZTIwNDZlYzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTQwOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg1NDRkM2NiNzljYTVjNGQzMDE1YzkyNzZjZmMwZWIzYmFkMWE3OWFiNzg3NDZkYzA2YzRlYjY3ZmI1YzFmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.89qyf1XYtC07ue4po2uF_ik6tDsx5j8T99_T6ktpb2k) [ ](https://private-user-images.githubusercontent.com/4519221/380744592-3db1c9c0-426b-45f7-9f18-970ee2046ec9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjQ4NzAsIm5iZiI6MTczMDEyNDU3MCwicGF0aCI6Ii80NTE5MjIxLzM4MDc0NDU5Mi0zZGIxYzljMC00MjZiLTQ1ZjctOWYxOC05NzBlZTIwNDZlYzkuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMTQwOTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg1NDRkM2NiNzljYTVjNGQzMDE1YzkyNzZjZmMwZWIzYmFkMWE3OWFiNzg3NDZkYzA2YzRlYjY3ZmI1YzFmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.89qyf1XYtC07ue4po2uF_ik6tDsx5j8T99_T6ktpb2k)
> 
> Part of my config
> 
> ```lua
> opts = {
>             R_app = "radian",
>             R_cmd = "R",
>             esc_term = true,
>             hl_term = false,
>             objbr_place = "console,below",
>             objbr_auto_start = false,
>             objbr_h = 20,
>             auto_start = "always",
>             auto_quit = true,
>             external_term = "/usr/bin/kitten @ --to unix:/tmp/kitty_sock launch --type window --location=vsplit --keep-focus --cwd=current",
> ```

I've tried to include your config into mine, except for `external_term` as I am using Windows and that would run `Rgui.exe` instead, but the issue persists.
Is it something to do with Neovim's built-in terminal and radian?

**Comment by PMassicotte** [comment]
What happens if you place your cursor on `diamonds` and type

```lua
lua require('r.send').line(false)
```

**Comment by dianchia** [comment]
> What happens if you place your cursor on `diamonds` and type
> 
> ```lua
> :lua require('r.send').line(false)
> ```

Still error, the output is as follow
```r
r$> diamonds %>%
        select(carat, price) %>%
            ggplot(aes(x = price, y = carat)) +
                geom_point() +
                    labs()

r$>         title = "Carat vs. Price",
Error: unexpected ',' in "        title = "Carat vs. Price","

r$>         x = "Price",
Error: unexpected ',' in "        x = "Price","

r$>         y = "Carat"

r$>     )
Error: unexpected ')' in "    )"

r$>
```

**Comment by PMassicotte** [comment]
It happens only when using radian + default nvim terminal?

**Comment by PMassicotte** [comment]
maybe related on how the terminal deals with end line characters?

**Comment by jalvesaq** [comment]
@dianchia could you try different values for the options from section 6.18. (_Control how paragraphs and lines are sent_) of `R.nvim` documentation?

**Comment by jalvesaq** [comment]
> I fiddle around with different values but no luck.

I expected that `bracketed_paste = true` would fix the issue.

> it seems like the parenthesis is auto-completed when sent to the R terminal

It looks like radian is reading the input one character at a time and autoclosing parentheses. Can you disable this feature?

**Comment by PMassicotte** [comment]
Here is my radian config file in case it helps.

```
options(
  radian.color_scheme = "everforest-dark",
  radian.editing_mode = "vi",
  radian.auto_suggest = FALSE,
  radian.vi_mode_prompt = "\033[0;34m[{}]\033[0m "
)
```

**Comment by jalvesaq** [comment]
Yes, `bracketed_paste = true` in the `R.nvim` config should fix it.

**Comment by dianchia** [comment]
> Yes, `bracketed_paste = true` in the `R.nvim` config should fix it.

The problem is that I've enabled it as seen from my config in the first comment.
```lua
return {
    "R-nvim/R.nvim",
    opts = {
        R_app = "radian",
        bracketed_paste = true,
    },
}
```

**Comment by dianchia** [comment]
> It seems that bracketed_paste doesn't work on Windows: https://github.com/REditorSupport/vscode-R/pull/149/files

I see... Guess there's no better way to solve this then. Thanks for the help! I'll close this issue for now.
