### ISSUE TITLE
Code completion possibly not R.nvim issue?

### ISSUE THREAD

**Issue by jasonpott** [R-nvim/R.nvim#260]
Since updating to the latest version I have noticed that there are some changes in the way that code completion is working in R.nvim. This is mainly to do with the location of the code completion and how they obscure the code that is currently being written.

I have included some screen shots of this to better demonstrate.

![image](https://github.com/user-attachments/assets/fac1fa1f-d621-4a31-9fda-1c55526a7bd0)
![image](https://github.com/user-attachments/assets/581f4e4d-fdc0-48d8-861e-f305c74c7de7)

I am working in wezterm on windows.
I am using cmp-r for completion

This may be a feature I have not understood so excuse me if this is the case.

**Comment by jalvesaq** [comment]
We only provide data to nvim.cmp, with no control over the completion
appearance or location.

**Comment by PMassicotte** [comment]
I never really noticed, but what has changed?

**Comment by jasonpott** [comment]
Thank you I'll investigate there.

Just the location of the completion pane. Previously it was not obscuring the cursor.
