### ISSUE TITLE
include visidata for data(frame) inspections

### ISSUE THREAD

**Issue by kraxli** [R-nvim/R.nvim#262]
Thanks for this great nvim plugin!

[visidat](https://www.visidata.org/) is a fantastic tool to inspect data for which a R-package exists [https://github.com/paulklemm/rvisidata](https://github.com/paulklemm/rvisidata). Would it possible to integrate [visidat](https://www.visidata.org/) in `R.nvim`?

**Comment by jalvesaq** [comment]
Please, see section 7 (_Public Lua API_) and the examples of section 8 (_Custom key bindings_) of `R.nvim` documentation.

**Comment by kraxli** [comment]
thanks @jalvesaq for the timely reply and highlighting the two sections! Is correct that the Lua API only allows to open e.g. a `data.frame` with `visidata` in the console itself? 
I was thinking more to open the `data.frame` with `visidata` in an extra split/floating window leveraging the `nvimcom.

**Comment by jalvesaq** [comment]
There are some examples in section 6.33 (_View a data.frame or matrix_).

**Comment by kraxli** [comment]
thanks again @jalvesaq ! While still taking the "detour" of writing first the `data.frame` to a file
```lua
csv_app = "terminal:vd"
```
works fine. :-) However 
```lua
 csv_app = ":TermExec cmd='vd %s'"
```
does not work, since `%` refers to the current `Rscript`-file and not the `tsv`-file holding the data of the `data.frame`.
E.g. if my `Rscript ` is called `test.r`, `cmd='vd %s'` results in the call `vd test.rs`

I have tested it on LinuxMint / Ubuntu using zsh-shell.

**Comment by jalvesaq** [comment]
I don't have the plugin that adds the `:TermExec` command, but looking at `R.nvim` code I could find a bug: the TSV file name was added twice for vim commands. Could you, please, try the branch "tsvnm_once"?

**Comment by jalvesaq** [comment]
I'm sorry, there was an error in the branch "tsvnm_once". I fixed it now.

**Comment by jalvesaq** [comment]
You can change the value of `csv_app` after startup with a command like this:

```vim
:lua require("r.config").get_config().csv_app = "other_csv_app"
```

But note that `csv_app` can be a Lua function. In that case, you could use whatever criteria you wanted to change the value of `csv_app` and, then, call `require('r.run').action('viewobj')`. Of course, you would need some familiarity with Lua.

**Comment by kraxli** [comment]
I have tried

```lua

...
csv_app = ':TermExec cmd="vd %s" direction=float'
...

function set_csv_app(app, mode, args)
  local default_app = require("r.config").get_config().csv_app
  require("r.config").get_config().csv_app = app
  require('r.run').action('viewobj', mode, args )
  -- require("r.config").get_config().csv_app = default_app
  return default_app
end
vim.api.nvim_buf_set_keymap(0, "n", <localleader>Vt, set_csv_app("terminal:vd", "n", ''), {})
```

which works :-) .

However, if I reset the default app  (uncommenting `require("r.config").get_config().csv_app = default_app`) after calling ` require('r.run').action()`, the "default app" is called. Is there another way to keep a default `csv_app`?

**Comment by jalvesaq** [comment]
Would it work if you disable the commands associated with the label `RViewDF`,

```lua
                disable_cmds = {
                    "RViewDF",
                },
```

then, create a map for it using your function?

```lua
vim.api.nvim_buf_set_keymap(0, "n", "<localleader>rv",
    set_csv_app(':TermExec cmd="vd %s" direction=float', "n", ''), {})
```

**Comment by kraxli** [comment]
thanks! this doesn't work as it calls `vd r_test.rs`, hence it calls the script name `r_test.r` and adds `s` instead of calling the  `data.frame` name

**Comment by PMassicotte** [comment]
oups, sorry miss-clicked.

By the way, any way to get working visidata with large dataframe? 

```r
library(nycflights13)
data(flights)
```

This takes a long time to open, possibly due to the writing to the tsv file which is needed.

**Comment by kraxli** [comment]
indeed it takes forever. This is due to writing the file.  In Python, I use `arrow` to write to a `parquet` file. Even large `dataframes` "load" pretty quickly. So I tried the same in R:

```R
system.time( arrow::write_dataset(flights, path = 'flights.parquet', format = "parquet") )
```
and in a terminal I run `vd flights.parquet`. All works pretty smooth :-)

**Comment by PMassicotte** [comment]
oh interesting, was not aware that `vd` could read parquet

**Comment by PMassicotte** [comment]
maybe we could had an option so user decide if they want to use arrow or write tsv

**Comment by jalvesaq** [comment]
Another option would be `fwrite()` from the `data.table` package. So, instead of special support for a specific library(`arrow` or `data.table`), a more generic approach could be better. Perhaps we could allow users to define the function to save the `data.frame`

**Comment by kraxli** [comment]
Allowing the users to define the function to save the data.frame would be a very flexible and sweet approach 😀

**Comment by jalvesaq** [comment]
Could you please try the branch "fix_df_viewer"? I fixed the option `df_viewer`, which was broken, but it should now work as documented.

**Comment by PMassicotte** [comment]
I like the idea. This that case does it mean that 

```r
csv_app = "R:tibble::tibble"
```

would use `write_csv()` ? How this would work with say `vd`? 

Could it be that we specify which R function to use AND which file format? Like `arrow`/`parquet` or `data.date`/`csv`?

**Comment by jalvesaq** [comment]
```lua
csv_app = "R:tibble::tibble"
```

would not save a `tsv`. It would send the command `tibble::tibble(obj)` to R Console, where `obj` is the name of the object if it is a `data.frame` or `matrix`. If you want to write the csv, you would have to create your own R function to save and display the `data.frame`.

I will make the changes...

**Comment by PMassicotte** [comment]
I get it. I will try to think of a solution to open a large `df` in an external utility like `vd` or whatever. It is currently slow to do it with a `df` that has more than 1e4 rows.

**Comment by jalvesaq** [comment]
Now you can try on the branch "fix_df_viewer":

```lua
  csv_app = "R:tibble::tibble",
```

**Comment by PMassicotte** [comment]
I am getting this:

```
Vim(lua):E5108: Error executing lua Vim:E475: Invalid value for argument cmd: 'R:tibble::tibble' is not executable         
stack traceback:                                                                                                           
        [C]: in function 'jobstart'                                                                                        
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:128: in function 'start'                                 
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/edit.lua:295: in function 'view_df'                              
        [string ":lua"]:1: in main chunk                                                                                   
        [C]: in function 'execute'                                                                                         
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:48: in function 'exec_stdout_cmd'                        
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:79: in function </home/filoche/.local/share/nvim/lazy/R.n
vim/lua/r/job.lua:58>                                                                                                      
stack traceback:                                                                                                           
        [C]: in function 'execute'                                                                                         
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:48: in function 'exec_stdout_cmd'                        
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:79: in function </home/filoche/.local/share/nvim/lazy/R.n
vim/lua/r/job.lua:58> function: builtin#18 Vim(lua):E5108: Error executing lua Vim:E475: Invalid value for argument cmd: 'R
:tibble::tibble' is not executable                                                                                         
stack traceback:                                                                                                           
        [C]: in function 'jobstart'                                                                                        
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:128: in function 'start'                                 
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/edit.lua:295: in function 'view_df'                              
        [string ":lua"]:1: in main chunk                                                                                   
        [C]: in function 'execute'                                                                                         
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:48: in function 'exec_stdout_cmd'                        
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:69: in function </home/filoche/.local/share/nvim/lazy/R.n
vim/lua/r/job.lua:58>                                                                                                      
stack traceback:                                                                                                           
        [C]: in function 'execute'                                                                                         
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:48: in function 'exec_stdout_cmd'                        
        /home/filoche/.local/share/nvim/lazy/R.nvim/lua/r/job.lua:69: in function </home/filoche/.local/share/nvim/lazy/R.n
vim/lua/r/job.lua:58>  

```

**Comment by PMassicotte** [comment]
Works fine!

**Comment by PMassicotte** [comment]
Do you think we could use the same principle (maybe something like `df_writer = arrow` to write the temp file on disk?

**Comment by jalvesaq** [comment]
We have to think about what options to use and how to name them.

The literal meaning of `csv_app` is the application to open the csv (actually, tsv) which can be Neovim, an external application, or R itself. In the last case, no csv is saved. Thus, the option name `csv_app` is inadequate.

When opening the csv in either Neovim or an external application, the algorithm is:

1. Save the csv.
2. Open the csv.

The option `csv_app` covers only the second step. So, perhaps we need another option: `csv_save_fun`. And to have options whose names match what they do, the options could be: `csv_save_fun`, `csv_app`, and `df_viewer_fun`.

What do you think?

**Comment by jalvesaq** [comment]
The branch now is "R_csv_app". I inadvertently started the other branch from the "rmd_params".

**Comment by PMassicotte** [comment]
> Another suggestion: the option becomes a table with three elements:
> 
> ```lua
> view_df = {
>     save_fun = "", -- Save the data.frame in a TSV file
>     open_app = "", -- Open the TSV in an application (Neovim or external application)
>     open_fun = "", -- Use an R function to open the data.frame directly (no conversion to TSV needed)
> },
> ```

I like it. `save_fun` would be an R function right? Then the user could use whatever they want and past the generated file to whatever function they want for visualization.

**Comment by jalvesaq** [comment]
> `save_fun` would be an R function right?

Yes.

> Then the user could use whatever they want and past the generated file to whatever function they want for visualization.

Not exactly because of the way it's currently implemented:

- Default behavior: The `data.frame` is streamed as a TSV file through the TCP connection to R.nvim which pastes it in a new tab. This is possibly the best option for those running R on a remote machine.
- When `csv_app` is set: the TSV file is saved and opened as specified in the option value.
- When `df_viewer` is set: Don't stream (and, of course, don't save) any TSV or CSV; pass the `data.frame` object directly as an argument to an R function.

If the user wants to save the `data.frame` using `arrow` and open it in Neovim or in an external application, he or she will have to write an R function for this.

I don't want to support either `arrow` or `data.table` directly because other users will prefer functions from other packages and request support for them. As usual with open-source projects, some libraries will become obsolete and soon R.nvim will be bloated with support for obsolete libraries. A custom function could also select only the first lines of a `data.frame` if it were too big.

**Comment by jalvesaq** [comment]
New suggestion of `view_df` table:

```lua
view_df = {
    csv_sep = "",  -- Field separator to be used when saving the CSV.
    n_lines = 2000,-- Number of lines to save in the CSV (0 for all lines).
    how = "tabnew", -- How to display the data within Neovim if not using an external application.
    save_fun = "", -- Save the data.frame in a CSV file
    open_app = "", -- How to open the CSV in Neovim or an external application.
    open_fun = "", -- Use an R function to open the data.frame
                   -- directly (no conversion to CSV needed)
},
```

With the options `n_lines` and `how`, we can delete the key bindings associated with the labels "RViewDFs", "RViewDFv", and "RViewDFa".

**Comment by jalvesaq** [comment]
> So save save_fun would be a R function that save the data into a csv/tsv?

I can implement it this way, to be used in combination with `open_app`.

**Comment by jalvesaq** [comment]
@kraxli, could you try the pull request #280 ?

**Comment by kraxli** [comment]
Thanks a lot @jalvesaq! I am just busy at work, but I am looking forward to trying it the next days. Sorry for being slow on this one.
