### ISSUE TITLE
Ordering of RMapsDesc output

### ISSUE THREAD

**Issue by sieste** [R-nvim/R.nvim#263]
Currently the output of `:RMapsDesc` starts with a section on Weave, then Commands, then Send and I have to scroll down quite a bit to see how to start an R session. I suggest to change the ordering a bit to reflect the priorities and workflow of a user learning to use the plugin.

**Comment by jalvesaq** [comment]
Currently, Lua randomly defines the order and I also don't like it. Please, try the branch "map_desc_by_cat".
