### ISSUE TITLE
[Feature] Add support for httpgd

### ISSUE THREAD

**Issue by AliSajid** [R-nvim/R.nvim#264]
I wanted to thank the team for this amazing plugin. It has made working in the R ecosystem so much easier for me.
I do have one request: Could you please integrate the `httpgd` plugin into this in a way that it can be opened transparently in the background? It's much easier to use and much cleaner for me on a MacBook. Thanks.

**Comment by PMassicotte** [comment]
You can do that in your `.Rprofile`.

```r
if (interactive() && Sys.getenv("RSTUDIO") == "") {
  Sys.setenv(TERM_PROGRAM = "vscode")
  if ("httpgd" %in% .packages(all.available = TRUE)) {
    options(vsc.plot = FALSE)
    options(device = function(...) {
      httpgd::hgd(silent = TRUE)
      .vsc.browser(httpgd::hgd_url(history = FALSE), viewer = FALSE)
    })
    httpgd::hgd()
  }
}
```

**Comment by jalvesaq** [comment]
I hadn't tried `httpgd` before, but with @PMassicotte code I could see that it opens a browser with the plots, and this is good not only for macOS users, but also for Linux users on Wayland wanting to avoid Xwayland.

The browser can be opened automatically with R:

```r
    .h <- utils::capture.output(httpgd::hgd())[2]
    .h <- sub(" *", "", .h)
    utils::browseURL(.h)
    rm(.h)
```

However, it would be better to start the browser when opening the first plot.

**Comment by PMassicotte** [comment]
I also made a keymap fpr opening it

```lua
set_keymap( "n", "<LocalLeader>g", "<cmd>RSend httpgd::hgd(); httpgd::hgd_browse()<CR>", { desc = "Start httpgd" })
```

**Comment by PMassicotte** [comment]
@AliSajid does modifying your `.Rprofile` fixes it? 

We could add an entry to the wiki.

**Comment by AliSajid** [comment]
Thank you everyone.

To respond:

1. @PMassicotte addition to the `~/.Rprofile` worked wonders. I have tweaked it to what @idavydov suggested, and it fits my workflow perfectly.
2. @idavydov I appreciate the remote setup link. I had seen it but disregarded parts of it because I did not think of my setup in server/client terms.
3. Please add this to the wiki. That would be great. I recommend the more concise version by @idavydov.

**Comment by jalvesaq** [comment]
@AliSajid, could you add it to the Wiki?

**Comment by AliSajid** [comment]
I've added the information to the [wiki](https://github.com/R-nvim/R.nvim/wiki/Configuration#using-httpgd-as-the-default-graphics-device). Thank you for the amazing work all of you are doing.
