### ISSUE TITLE
csv_app = ":TermExec cmd='vd %s'" is not working on MS-Windows

### ISSUE THREAD

**Issue by kraxli** [R-nvim/R.nvim#268]
`csv_app = ":TermExec cmd='vd %s'"` is not working on MS-Windows.

I am using  MS Windows 10 and have tried several terminals / shells in Windows.

![image](https://github.com/user-attachments/assets/5ddfec3d-165a-4169-be8f-7c76791f97ed)

`csv_app = "terminal:vd"` works :-)

**Comment by jalvesaq** [comment]
Does it work if you manually create an `example.tsv` file and do the command
 `:TermExec cmd='vd example.tsv'`?

**Comment by jalvesaq** [comment]
Thanks for the feedback! I will change the example in the documentation.
