### ISSUE TITLE
r.nvim / nvimcom installation has failed on Windows

### ISSUE THREAD

**Issue by kraxli** [R-nvim/R.nvim#269]
`r.nvim / nvimcom` installation has failed on Windows 10, 64bit. 

I made it work by adding line `95` of the file `src/nvimcom.c` to `ifdef WIN32`condition. 
![image](https://github.com/user-attachments/assets/0266ae9f-356d-454f-9748-c8deafc57377)

Is potentially the `Makefile.win` not `WIN64` ready?

![image](https://github.com/user-attachments/assets/3dc2d05d-35fc-40fa-b922-4049c0680dc3)

**Comment by jalvesaq** [comment]
Thanks for reporting the bug and trying to fix it!

The flag `WIN32` refers to Windows (both 32-bit and 64-bit). The flag `WIN64` is used to differentiate the few things that change from 32-bit to 64-bit.

The variable `flag_glbenv` is meaningful only on Unix. So, the correct fix is to run `nvimcom_globalenv_list()` immediately but only if R is not busy doing something else. I no longer have access to Windows. So, could you please try the branch "win_glbenv" and report if it works?

**Comment by kraxli** [comment]
many thanks @jalvesaq! The installation seems to work :-)

**Comment by jalvesaq** [comment]
Thanks for trying it!
