### ISSUE TITLE
Tasks to do before inaugurating R.nvim

### ISSUE THREAD

**Issue by jalvesaq** [R-nvim/R.nvim#27]
Here are some tasks that I foresee:

  - ~~Send Lua table instead of Vim list, Vim dictionary, or white space separated list of words to `job.stdout`, and use `lua cmd` instead of `call v:lua.`.~~ Done on data sent to `cmp-r` which is the only one that requires high speed.

  - ~~Create the `R.nvim` organization with the repository `cmp-r`.~~ Done.

  - ~~Do `grep -R '\\|' lua/` and fix patterns that don't work.~~

  - ~~Use `vim.regex` or `vim.fn.matchlist()` to fix code that uses patterns `\k` or `\w`~~

  - Fix ~~all~~ most `FIXME`. OK, the remaining might be fixed later.

  - ~~Add "desc" field to maps.~~

  - ~~Temporarily force `rnvimserver` to send strings broken in pieces to fully test `job.stdout()`.~~ Simpler than that: I did `<LocalLeader>o` over a character vector with 10000 lines with R running in a remote machine. The data arrived in three parts, and the function worked properly.

  - Test everything.

  - ~~Visit open issues in `Nvim-R` requesting new features and invite people to try `tmp-R-Nvim` for a week.~~. Done.

  - One week later:

    - Add the repository R.nvim to the organization.

    - ~~Close issues in Nvim-R that are too old, aren't reproducible, or won't be fixed, and invite people to switch to `R.nvim` (where there is a chance of the bug being fixed).~~ Already done.

**Comment by jalvesaq** [comment]
I think we are ready to create the `R.nvim` organization with the project `cmp-r`...
@PMassicotte ? @she3o ?

**Comment by PMassicotte** [comment]
For me it is in a state that is very usable. So I am up for it :)

**Comment by jalvesaq** [comment]
I created the organization. Its "display name" is "R.nvim", but it seems that the URL cannot have a dot in the name. Github created https://github.com/R-nvim instead. So, maybe we should change the name of the organization to "R-nvim"...

@PMassicotte , I invited you to the organization.
@she3o , I will invite you if you are still interested in being part of the organization.

**Comment by jalvesaq** [comment]
The organization can't be "R.nvim", but the repository can.

**Comment by she3o** [comment]
>  @she3o , I will invite you if you are still interested in being part of the organization.

Of course, I'd be delighted to join. I must apologize for the frequent interruptions in communication. Balancing postgraduate studies and work commitments has significantly limited my availability on GitHub. However, I'll make every effort to contribute by submitting pull requests whenever possible.

**Comment by jalvesaq** [comment]
Initially, I intended to copy the files from this repository to `R-nvim`, starting the new repository `R.nvim` as a simple conversion from VimScript to Lua. But now we have not only the conversion of old code, but new code written by @PMassicotte, @she3o, and @hongyuanjia. So, now I prefer to keep the git history of your contributions, and, in this case, we can immediately transfer the repository to the new organization. I still prefer to squash all consecutive commits by the same author in single commits, to begin with a cleaner git history.

What do you think?

**Comment by PMassicotte** [comment]
Perfectly fine with me, this seems fair enough. :+1:

**Comment by she3o** [comment]
yep, let's do it.

**Comment by jalvesaq** [comment]
I did my first squash with gitlazy, it seems to be OK. In a few minutes, I will continue...

**Comment by jalvesaq** [comment]
I managed to decrease the number of commits from about 280 to 178, but, then, some conflicts appeared again and again.

**Comment by jalvesaq** [comment]
An atempt of using `git rerere` broke everything. I will restore the files from my backup...

**Comment by hongyuanjia** [comment]
Rewriting git history is a real pain...

**Comment by jalvesaq** [comment]
I restored the files. Using `diff -aur` to compare my backup with the `tmp-R-Nvim` repository, it seems that everything is OK.

**Comment by jalvesaq** [comment]
The repository is at its new address.
