### ISSUE TITLE
edit() to open file in existing neovim

### ISSUE THREAD

**Issue by iagomosqueira** [R-nvim/R.nvim#273]
The same way `help()` is redirected to a new buffer in the existing neovim session, could this be done for calls to `edit()`?

**Comment by iagomosqueira** [comment]
Maybe I should move this to a discussion?

**Comment by jalvesaq** [comment]
We have this in `R.nvim` documentation:

_R.nvim sets the option "editor" to a function that makes the object to be edited in a new tab when `esc_term` = `true` (the default value)._

**Comment by iagomosqueira** [comment]
Thanks, missed that. I'll check once I get the whole setup to work

**Comment by danwwilson** [comment]
I've been trying to use the edit command to open a file from a function but it seems to open in the R terminal in a strange way. 
the command I'm using is `edit(file = "myfile.R", editor = "nvim"). The intention is to call this from a function to open a file, similar to the `rstudioapi::navigateToFile()` function.

**Comment by danwwilson** [comment]
Thanks for the feedback an guidance. I'll explore a few options to see if I can make it work how I'd like.
