### ISSUE TITLE
Can't quit active shiny session

### ISSUE THREAD

**Issue by kkanden** [R-nvim/R.nvim#274]
I am currently developing a shiny application. When running `shiny::runApp()` in the console the app opens properly in the browser, however, even after closing the browser tab and running `:RStop` and `:RKill`, the console is still busy. To make the console available again I have to quit neovim altogether.

**Comment by jalvesaq** [comment]
Please, see this: https://github.com/jalvesaq/Nvim-R/issues/487

**Comment by kkanden** [comment]
Thanks a lot,
Doing `i`, `Enter` and `Ctrl+c` in the terminal worked perfectly :D
