### ISSUE TITLE
Error: params object already exists in knit environment so can't be overwritten by render params

### ISSUE THREAD

**Issue by idavydov** [R-nvim/R.nvim#276]
I'm getting an error when calling "knit current document and generate the default document format" if the R Markdown has `params` defined.

A minimal document:

````md
---
params:
  a: 1
---

```{r}
cat("hi\n")
```
````

Steps to reproduce:
1. Open the R Markdown.
2. Start R.
3. `<LocalLeader>kr`

Output:
```
> nvim.interlace.rmd("x.Rmd", rmddir = "/home/<...>", envir = .GlobalEnv)
Error: params object already exists in knit environment so can't be overwritten by render params
```

**Comment by jalvesaq** [comment]
On the branch "rmd_params", the `params` object is deleted before calling `rmarkdown::render()` and restored afterward. Could you, please, try it and report any side effects?

**Comment by idavydov** [comment]
Thanks, @jalvesaq! Seems to work fine for now, but I would prefer to test a bit more.

**Comment by jalvesaq** [comment]
There is a pull request for this: #281

**Comment by idavydov** [comment]
I was testing the branch for a bit and didn't observe anything suspicious. So looks good from my perspective, thanks @jalvesaq !

**Comment by jalvesaq** [comment]
Thanks! I will merge it.
