### ISSUE TITLE
R break command (<c-d>) in R.nvim terminal kills the terminal

### ISSUE THREAD

**Issue by kraxli** [R-nvim/R.nvim#277]
in a regular `R`-terminal I can break a miss-specified command (e.g. not closing brackets `c(1, 2, `  ) by the key mapping `<c-d>`. In the `R.nvim`-terminal `<c-d>` kills the terminal. To me, this is `R.nvim` specific and happens on Linux and Windows. 

Is there another way to break a miss-specified command  in a `R.nvim`-terminal or how can I disable `<c-d>` for `R.nvim`-terminals?

**Comment by jalvesaq** [comment]
What happens after `<c-d>` when you manually split the window (`<c-w>v`) and start R (`:terminal R`)?

**Comment by kraxli** [comment]
with `:terminal R` all works as expected

**Comment by jalvesaq** [comment]
When I press `<c-d>` on the R Console, R quits. The result is the same when running R directly in a terminal emulator (Kitty), with R started by `R.nvim` in TERMINAL mode, and with R running from the command `:terminal R` also in TERMINAL mode.

**Comment by kraxli** [comment]
I use `zsh` / `bash` and `Windows Terminal`. Pressing `<c-d>` in `:terminal R` the behavior depends on the state:

1. "prompt" mode (`>`): I am asked to "save the workspace", "quit without saving" or "cancel". 
2. In a "faulty / incomplete" input state (`+` at the beginning of the input prompt), e.g.  not having closed a bracket: By pressing `<c-d>`, the "faulty / incomplete" input state is left, and the mode is back to the "normal prompt" mode (`>`).

Pressing `<c-d>` in `R.nvim` closes `R` and the terminal window independent of the state / mode.

**Comment by kraxli** [comment]
thanks @jalvesaq for sparring! 

I had 
```lua
R_args = { "--no-save" },
```
in my `R.nvim` config which caused the behavior described above. **Without** `R_args = { "--no-save" }` all works as expected :-)
