### ISSUE TITLE
nvimcom failed to install with outdated R packages

### ISSUE THREAD

**Issue by jranke** [R-nvim/R.nvim#287]
I was testing R.vim with the current stable appimage version of neovim (v. 0.10.2) on Debian bookworm. The plugin is loaded with lazy.lua, my configuration is on github [1]. When I open an R file, the plugin is loaded fine, but when updating `nvimcom`, I got

```
ERROR: R exit code = 1! Please, run :RDebugInfo for details. 
```
Looking at the suggested `:RDebugInfo` reveals that the nvimcom can't be loaded.

```
Time:                                                                                                                                                                                         
  unix setup: 1.0961e-05                                                                                                                                                                                
  before_rns.R (async): 2.386758657                                                                                                                                                                     
  global setup: 0.000598898                                                                                                                                                                             
  check health (async): 0.000264353                                                                                                                                                                     
Why build nvimcom: nvimcom version mismatch                                                                                                                                                             
before_rns.R stdout: (empty)                                                                                                                                                                            
before_rns.R stderr: .build_packages() exit status 0* installing to library ‘/usr/local/lib/R/site-library’* installing *source* package ‘nvimcom’ ...** using staged installation** libsusing C compile
r: ‘gcc (Debian 12.2.0-14) 12.2.0’installing via 'install.libs.R' to /usr/local/lib/R/site-library/00LOCK-nvimcom/00new/nvimcom** R** byte-compile and prepare package for lazy loading** help*** instal
ling help indices** building package indices** testing if installed package can be loaded from temporary locationERROR: loading failed* removing ‘/usr/local/lib/R/site-library/nvimcom’* restoring prev
ious ‘/usr/local/lib/R/site-library/nvimcom’Error in do_exit(status = status) : .install_packages() exit status 1* removing ‘/usr/local/lib/R/site-library/nvimcom’Error in do_exit(status = status) : .
install_packages() exit status 1Execution halted
```

While writing this bug report, I updated all my installed packages and tried again. After that, I got a different message in `RDebugInfo` which told me that I should update the `colorout` package, because my version was apparently built before R 4. So I did that, and - voilá, the plugin worked! So I am just submitting this issue for the records, and will close it immediately afterwards. I do not know which packages actually needed an update for the installation of `nvimcom` to work, but as there are only few non-base dependencies, (`knitr`, `rmarkdown`, `quarto`), it might have been one of those.

[1] https://github.com/jranke/dotfiles/tree/nvim-lua

**Comment by jalvesaq** [comment]
I'm glad to see you here! Thanks for reporting the issue and how you managed to fix it!

**Comment by mpadge** [comment]
Thanks @jranke, I just spent half a day debugging same error as #420. With no information to help at all, I spent half a day trying to debug my nvim config before stumbling across your comment here, which solved everything! Updated `colorout` and `nvimcom` and everything works again 🚀
