### ISSUE TITLE
Can't insert the `<-` operator

### ISSUE THREAD

**Issue by XavierLaRochelle** [R-nvim/R.nvim#289]
I just installed the plugin and I was trying it out. I use Lazy as a plugin manager and my config file looks like this : 
```lua
return {
  "R-nvim/R.nvim",
  version = "~0.1.0",
  opts = {
    auto_start = "on startup",
  },
}
```

When I try to use the keymap to insert the `<-` operator in insert mode, I get the following error message : 
```
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:116: Parser could not be created fo
r buffer 1 and language "r"
stack traceback:
        [C]: in function 'error'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:116: in function 'get_parser'
        /Users/xlr/.local/share/nvim/lazy/R.nvim/lua/r/utils.lua:68: in function 'get_lang'
        /Users/xlr/.local/share/nvim/lazy/R.nvim/lua/r/edit.lua:11: in function 'assign'
        [string ":lua"]:1: in main chunk
```

Not sure if this is a treesitter of R.nvim problem but I was wondering if this happened to anyone else?

**Comment by jalvesaq** [comment]
Unfortunately, we can't fix bugs in R.nvim 0.1.0.  Could you please remove the plugin and install it again without the field `version = "~0.1.0"`?

**Comment by XavierLaRochelle** [comment]
I understand.
I tried removing it but I still get the same error message.

**Comment by jalvesaq** [comment]
Did you install the required tree-sitter parsers?

**Comment by XavierLaRochelle** [comment]
It wasn't installed and installing it solved the issue! I now realize it was mentioned in the documentation so apologies for missing that part. 

Thanks for the help!

**Comment by jalvesaq** [comment]
You are welcome!
