### ISSUE TITLE
R terminal crash on qmd  open or  leader RF

### ISSUE THREAD

**Issue by jasonpott** [R-nvim/R.nvim#294]
Hi 

In the last couple of days I have been having difficulties working with quarto files on windows.

When I select a QMD file and then initiate an R terminal the following error is returned:

Warning: stack imbalance in '::', 71 then 69
Warning: stack imbalance in '$', 68 then 66 
[Process exited -1073741784]

If I first open an R file I am able to initialise the R terminal.

But when I then open a Quarto file I get the following error

> Error: '\R' is an unrecognized escape in character string (<input>:1:29)

[Process exited -1073741784]

I am happy to provide additional information if you can let me know what would be useful.

Many thanks.

**Comment by jalvesaq** [comment]
This usually happens when an R command sent by `R.nvim` through the TCP connection is evaluated by `nvimcom` while R is busy doing something else.

Do you have the `params` field in the YAML header of your Quarto document?

Please, put in your `~/.Rprofile`:

```r
options(nvimcom.verbose = 6)
```

This will allow you to see what commands are being sent from `R.nvim` to `nvimcom`.

**Comment by jasonpott** [comment]
Hi Thank you I have added this to the .Rprofile

I do have some params in this qmd file:

error message is 
`
Warning: stack imbalance in '$', 62 then 65
Error: '\R' is an unrecognized escape in character string (<input>:1:29)

[Process exited -1073741784]
`

In a qmd without parameters the file loads and the R terminal opens without error and I can send commands.

**Comment by jalvesaq** [comment]
Could you give an example of `params` field that causes the bug, please?  I need this information to replicate and fix the bug.

**Comment by jasonpott** [comment]
Of course apologies I should have uploaded this earlier.

`
---
format:
  pdf:
    toc: true
    documentclass: report
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 20mm
    margin-bottom: 20mm
params:
  pc_search: true
  pc_1: "267102003"
  pc_2: "421581006"
  pc_3: "40739000"
  start_date: "2023-01-01"
  end_date: "2024-08-31"
  disease: "Sore Throat"
title: "Summary data for `r params$disease` presentations from `r params$start_date` - `r params$end_date`"
author: "Jason Pott"
---

```{r}
pc_codes <- c(
  if(!is.null(params$pc_1)){params$pc_1},
  if(!is.null(params$pc_2)){params$pc_2},
  if(!is.null(params$pc_3)){params$pc_3}
)

```
`

Note that the crash occurs in files where there are not parameters in the title.

**Comment by jalvesaq** [comment]
There is no bug here (Linux). The code to get the params worked for you when it was first implemented. Maybe this commit introduced the bug on Windows:

https://github.com/R-nvim/R.nvim/commit/dd122b8a5f1e2b7eb79a6181b306e5aa7be6c950

**Comment by jasonpott** [comment]
Would you be able to tell me how I could revert to the prior version to test this? Would I fork at an earlier version and load that in place of R.nvim?

**Comment by jasonpott** [comment]
Super thank you - I reverted to this commit and the Rterm opens as normal

![image](https://github.com/user-attachments/assets/be57c419-51cf-4a6b-9d43-77a98fb2154e)

**Comment by jalvesaq** [comment]
I had an idea: set params while loading nvimcom. It works on Linux. On Windows, it may either work or crash R even early. Could you please try the branch `early_params`?

**Comment by jasonpott** [comment]
OK will look and report back.

**Comment by jasonpott** [comment]
This branch loaded the parameters into the environment and everything is working as expected.

**Comment by jalvesaq** [comment]
Thanks for trying it! I had no access to my notebook yesterday, but I will make a pull request now.
