### ISSUE TITLE
Rnoweb: Error: unexpected input in "<<"

### ISSUE THREAD

**Issue by rg-ch** [R-nvim/R.nvim#298]
![image](https://github.com/user-attachments/assets/d896fbb5-1337-4ea8-90f7-089a6128e745)

Thank you very much for R.nvim at all the work done. I'm using r.nvim and the same configuration for rmd files without problems, but in rnoweb files I'm observing the following behavior.

When I send the **first** line after a chunk , see line 10 (via 	vim.api.nvim_buf_set_keymap(0, "n", "<Space>", "<Plug>RDSendLine", {}) ) i have an error message, but the next one (line 11) can be sent without error message.
The command is correctly executed and i can also knit the pdf correctly. It's not a real bug.

I tried also with minimal configuration. I had the same "error". 

I also remarked that in rmd  the autocomplete for chunk options is working, this is not the case for rnoweb files. I don't know if this maybe related.

:set filetype? -> rnoweb (filetype is recognized)

I added roman2.txt which is indeed a rnoweb file (roman2.rnw).

[roman2.txt](https://github.com/user-attachments/files/18261070/roman2.txt)

Can you reproduce this or do you have a solution.

Thanks

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. I can replicate it. Also, I don't get syntax highlight of R chunks (and I noted that you are getting legacy Vim syntax highlighting because `data.frame` is green while other function names are blue). Both problems are solved if the chunk is written as:

```
<<boringp>>=
#| fig.label: "test"
#| fig.width: 4
#| fig.height: 4
#| out.width: '.4\\linewidth' 

x <- 1 + 1
d <- data.frame(x=2,d=3)

par(mar = c(4, 4, .2, .2))
plot(rnorm(100))
@
```

Since this is the result of a tree-sitter feature/limitation, I will add the issue and the workaround to the _Known bugs_ section of `R.nvim` documentation.

**Comment by rg-ch** [comment]
Thank you very much for your answer. 

I replaced  the chunk with your chunk but I the error message doesn't disappear even with  the attached configuration, which is of the mostly part a copy of the proposed configuration in the wiki.
Do you you have a hint why this workaround doesn't work for me ?

Best regards
Roman

[roman3.txt](https://github.com/user-attachments/files/18262331/roman3.txt)
[initlua.txt](https://github.com/user-attachments/files/18262353/initlua.txt)

![image](https://github.com/user-attachments/assets/51204710-4c82-43c7-9bd8-91ba0be393c9)


![image](https://github.com/user-attachments/assets/ad1ee0ba-8fa0-48bf-938b-ff34bcd81cfd)
![image](https://github.com/user-attachments/assets/3bc75504-50a9-458d-91ed-71d688981700)

nvim -V1 -v
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection     -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/neovim/src=/usr/src/debug/neovim -flto=auto -O2 -g -Og -g -flto=auto -fno-fat-lto-objects -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -Wno-conversion -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always  -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim/src/neovim/build/src/nvim/auto -I/build/neovim/src/neovim/build/include -I/build/neovim/src/neovim/build/cmake.config -I/build/neovim/src/neovim/src 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by jalvesaq** [comment]
Strangely, I now have the same bug with my configuration... It seems that the tree-sitter has changed. I'm trying to fix the issue.

**Comment by jalvesaq** [comment]
The code works if I put this debugging command:

```lua
    if node then vim.notify("node_type: '" .. node:type() .. "'") end
```

Since we can't have such a debugging command in the code, I tried this and it seems to work:

```lua
    if node then vim.schedule(function() end) end
```

The above command schedules a function that does nothing to run when Neovim is idle.

Could you, please, try the branch "strange_fix"?

**Comment by rg-ch** [comment]
Thanks a lot the "strange_fix" works with the minimal load (below) and my own configuration. 

![image](https://github.com/user-attachments/assets/a2f2c44f-1aae-4bbe-b5c2-8763c968ef3d)


1) Am I right, that chunk autocomplete (e.x fig.caption ..., fig.width) doesn't exist in rnoweb files using |# 
2)  In Rmd `` expands to the whole chunk delimiters. **Does "<"  Rnoweb completion of code block work for you in our test file**.  I can't make it work. RConfigShow  (see below) : rnowebchunk = true (default configuration, isn't it). 
If it does do you have an idea, what might be wrong in my case

**Tell me if you want me  to create a new issue  in order to prevent mixing up issues.**

Thanks in advance

Result of my  : RConfigShow

{
  OutDec = ".",
  RStudio_cmd = "",
  R_Tmux_pane = "%0",
  R_app = "R",
  R_args = { "--no-save" },
  R_cmd = "R",
  R_continue_str = "+",
  R_path = "",
  R_prompt_str = ">",
  Rout_more_colors = false,
  applescript = false,
  arrange_windows = false,
  assignment_keymap = "<M-->",
  auto_quit = true,
  auto_scroll = true,
  auto_start = "no",
  bracketed_paste = false,
  buffer_opts = "winfixwidth winfixheight nobuflisted",
  clear_console = true,
  clear_line = false,
  close_term = true,
  compl_data = {
    max_depth = 3,
    max_size = 1000000,
    max_time = 100
  },
  compldir = "/home/romanjro/.cache/R.nvim",
  config_tmux = true,
  convert_range_int = false,
  curview = "None",
  disable_cmds = { "RClearConsole", "RCustomStart", "RSPlot", "RSaveClose" },
  editing_mode = "emacs",
  esc_term = true,
  external_term = false,
  has_X_tools = true,
  hl_term = true,
  hook = {
    on_filetype = <function 1>
  },
  insert_mode_cmds = false,
  is_darwin = false,
  is_windows = false,
  latexcmd = { "default" },
  listmethods = false,
  local_R_library_dir = "",
  localtmpdir = "/dev/shm/R.nvim-romanjro",
  max_paste_lines = 20,
  min_editor_width = 72,
  nvimpager = "split_h",
  objbr_allnames = false,
  objbr_auto_start = false,
  objbr_h = 10,
  objbr_mappings = {
    p = "plot",
    s = "summary"
  },
  objbr_opendf = true,
  objbr_openlist = false,
  objbr_place = "script,right",
  objbr_placeholder = "{object}",
  objbr_w = 40,
  open_example = true,
  open_html = "open and focus",
  open_pdf = "open and focus",
  paragraph_begin = true,
  parenblock = true,
  path_split_fun = "file.path",
  pdfviewer = "zathura",
  pipe_keymap = "<localleader>,",
  pipe_version = "native",
  quarto_preview_args = "",
  quarto_render_args = "",
  rconsole_height = 15,
  rconsole_width = 78,
  register_treesitter = true,
  remote_compldir = "",
  rm_knit_cache = false,
  rmarkdown_args = "",
  rmd_environment = ".GlobalEnv",
  rmdchunk = 2,
  rmhidden = false,
  rnowebchunk = true,
  rnvim_home = "/home/romanjro/.local/share/nvim-lazyvim/lazy/R.nvim",
  routnotab = false,
  rproj_prioritise = { "pipe_version" },
  save_win_pos = false,
  set_home_env = true,
  set_params = "yes",
  setwd = "no",
  setwidth = 2,
  silent_term = false,
  skim_app_path = "",
  source_args = "",
  source_read = "/dev/shm/R.nvim-romanjro/Rsource-4102",
  source_write = "/dev/shm/R.nvim-romanjro/Rsource-4102",
  specialplot = false,
  start_libs = "base,stats,graphics,grDevices,utils,methods",
  synctex = true,
  term_pid = 2520,
  term_title = "Terminal - romanjro@romanl7450:/home/roman/stadec/data/tribunal/ge_impec",
  texerr = true,
  tmpdir = "/dev/shm/R.nvim-romanjro",
  uname = "Linux",
  user_login = "romanjro",
  user_maps_only = false,
  uservimfiles = "/home/romanjro/.local/share/nvim-lazyvim/lazy/R.nvim",
  view_df = {
    csv_sep = "",
    how = "tabnew",
    n_lines = -1,
    open_app = "",
    open_fun = "",
    save_fun = ""
  },
  wait = 60
}

**Comment by jalvesaq** [comment]
> Thanks a lot the "strange_fix" works with the minimal load (below) and my own configuration.

Thanks! I will make the pull request.

> Am I right, that chunk autocomplete (e.x fig.caption ..., fig.width) doesn't exist in rnoweb files using |#

The autocomplete of chunk options works in `rnoweb` on my side. It's better to open a new issue for this. Usually, I'm not worried about mixing the fixes of two or more issues in a single pull request, but this time I've made a reference to this issue in the documentation. So, it's better to keep it short.

> In Rmd `` expands to the whole chunk delimiters. Does "<" Rnoweb completion of code block work for you in our test file.

This is a new bug. The function that gets the current language used to return "rnoweb". Now, it returns "latex". I'll fix it directly on the main branch. We need a pull request for the "strange_fix" because I don't know how it will work on macOS and Windows since we are circumventing what seems to be a Neovim or tree-sitter bug.

**Comment by jalvesaq** [comment]
> I've made a reference to this issue in the documentation

No, I didn't. I guess I deleted the reference to this issue before committing the change in the documentation.

**Comment by rg-ch** [comment]
It works "<" completes to

<<>>=
@
as described in  [6.6. Rnoweb completion of code block]( https://github.com/R-nvim/R.nvim/blob/main/doc/R.nvim.txt) 

Thank you
