### ISSUE TITLE
rnoweb chunk , how to trigger autocomplete of #| 

### ISSUE THREAD

**Issue by rg-ch** [R-nvim/R.nvim#300]
How can I trigger the autocomplete e.x echo=false in the following rnoweb chunk on a new line #| or on a existing line . 
I have the following chunk in my file roman3.rnw (attached as roman3.txt) with configuration init.lua attached as initlua.txt

[roman3.txt](https://github.com/user-attachments/files/18266233/roman3.txt)
[initlua.txt](https://github.com/user-attachments/files/18266234/initlua.txt)

<< boringp >>=
#| fig.label: "test" 
#| fig.width: 4
#| fig.height: 4
#| out.width: '.4\\linewidth' 

x <- 1 + 1
d <- data.frame(x=2,d=3)
par(mar = c(4, 4, .2, .2))
plot(rnorm(100))
@

Unfortunately, I don't really understand all the mechanics of the configuration file. In Rmd chunks autocomplete works.  
Is there something missing in my init.lua.
Thanks in advance for the hint.

**Comment by jalvesaq** [comment]
From your `init.lua`:

- southernlights is not installed.
- The command `vim.cmd 'noremap <F5> <Esc>:syntax sync fromstart<CR>'` will not be useful because we are using tree-sitter highlighting.

Other than that, you `init.lua` is good. The autocompletion is being triggered on my side:

![image](https://github.com/user-attachments/assets/70b63758-9e58-4fdf-b324-e2d3baa9042c)

Since the `southernlights` colorscheme was working, you should check your `~/.config/nvim` directory. Maybe you have something there preventing `cmp-r` of working properly.

You can also look at the output of `:checkhealth`...

**Comment by jalvesaq** [comment]
Also:
- You are creating some global Lua variables and not using them: `latexcmd` and `synctex`.
- It's better to add "latex" to the list of required tree-sitter parsers (I just added it to the README and `doc/R.nvim.txt`).

**Comment by rg-ch** [comment]
Hello, 
Thank you very much for your help.

I removed cmp-r and added it
I added latex via TSInstall  and later in _Parser/Features_ latex is also listed
**I don't find the solution** 

in the config file you write as a comment:

  _-- During auto-completion, press <Tab> to select the next item._ 

whe I write "e" and then tab i have the following message in console 

![image](https://github.com/user-attachments/assets/0649cb2f-b59c-4771-a8c2-df6ed993bc4e)


Maybe this is related to my missing popup.menu for autocomplete.

**Please can you have a quick look at the pasted _checkhealth_, but I understand if you can give me further assistance.
I dont know where to find the error.**


: TSInstallInfo gives me:

latex              [✓] installed

**but in : checkhealth 
it doesn't appear** 


Checking tree-sitter parsers: ~
- OK `r`  found.
- OK `markdown`  found.
- OK `markdown_inline`  found.
- OK `rnoweb`  found.
- OK `yaml`  found.




lazy: require("lazy.health").check()

lazy.nvim ~
- {lazy.nvim} version `11.16.2`
- OK {git} `version 2.47.1`
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

luarocks ~
- checking `luarocks` installation
- OK no plugins require `luarocks`, so you can ignore any warnings below
- OK {luarocks} `/usr/bin/luarocks 3.11.1`
- WARNING `lua` version `5.1` needed, but found `Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio`
- WARNING {lua5.1} or {lua} or {lua-5.1} version `5.1` not installed

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/share/nvim/runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $VTE_VERSION="7802"
- $COLORTERM="truecolor"

External Tools ~
- OK ripgrep 14.1.1 (/usr/bin/rg)

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.6 (21a517c423010811147b0b1aa1e7aedc39ce91aa) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v23.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.2.1 20240910
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.65-1-MANJARO",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed Dec 11 22:24:04 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - csv                 ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - rnoweb              ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
provider.clipboard: require("provider.clipboard.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: xsel

==============================================================================
provider.node: require("provider.node.health").check()

Node.js provider (optional) ~
- Node.js: v23.3.0
  
- WARNING Missing "neovim" npm (or yarn, pnpm) package.
  - ADVICE:
    - Run in shell: npm install -g neovim
    - Run in shell (if you use yarn): yarn global add neovim
    - Run in shell (if you use pnpm): pnpm install -g neovim
    - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

==============================================================================
provider.perl: require("provider.perl.health").check()

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim
- WARNING No usable perl executable found

==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- `g:python3_host_prog` is not set. Searching for python3 in the environment.
- Executable: /usr/bin/python3
- Python version: 3.12.7
- pynvim version: 0.5.1
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV

==============================================================================
provider.ruby: require("provider.ruby.health").check()

Ruby provider (optional) ~
- Ruby: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

==============================================================================
r: require("r.health").check()

Checking applications and plugins: ~
- OK Neovim version: 0.10.2+v0.10.2
- OK C compiler (`gcc` or `clang`) found.
- OK `R-nvim/cmp-r` found.
- OK `nvim-treesitter/nvim-treesitter` found.

Checking tree-sitter parsers: ~
- OK `r`  found.
- OK `markdown`  found.
- OK `markdown_inline`  found.
- OK `rnoweb`  found.
- OK `yaml`  found.

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/romanjro/.local/state/nvim-lazyvim/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

vim.lsp: File Watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

vim.lsp: Position Encodings ~
- No active clients

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: bash                 ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/bash.so
- OK Parser: bibtex               ABI: 13, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/bibtex.so
- OK Parser: c                    ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/c.so
- OK Parser: css                  ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/css.so
- OK Parser: csv                  ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/csv.so
- OK Parser: html                 ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/html.so
- OK Parser: json                 ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/json.so
- OK Parser: latex                ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/latex.so
- OK Parser: lua                  ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/markdown_inline.so
- OK Parser: python               ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/python.so
- OK Parser: query                ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/query.so
- OK Parser: r                    ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/r.so
- OK Parser: rnoweb               ABI: 13, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/rnoweb.so
- OK Parser: vim                  ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/vimdoc.so
- OK Parser: yaml                 ABI: 14, path: /home/romanjro/.local/share/nvim-lazyvim/lazy/nvim-treesitter/parser/yaml.so
- OK Parser: c                    ABI: 14, path: /usr/share/nvim/runtime/parser/c.so
- OK Parser: lua                  ABI: 14, path: /usr/share/nvim/runtime/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /usr/share/nvim/runtime/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /usr/share/nvim/runtime/parser/markdown_inline.so
- OK Parser: query                ABI: 14, path: /usr/share/nvim/runtime/parser/query.so
- OK Parser: vim                  ABI: 14, path: /usr/share/nvim/runtime/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /usr/share/nvim/runtime/parser/vimdoc.so

**Comment by jalvesaq** [comment]
From the `~/.local/share/nvim/lazy` directory, the output of `grep -R has_words_before` is:

```
lsp_signature.nvim/tests/init_paq.lua:      elseif has_words_before() then
```

The problem seems to be in `lsp_signature.nvim`, not in `cmp-r` or `R.nvim`.

**Comment by rg-ch** [comment]
Thank for your hint.

If you don't use the tab-feature, do I need lsp_signature  for chunk completing if I don't need it for data.frame completing.  Chunk completing inside ``` for rmd works great. Is this so different with #|

I don't understand why auto-complete works for data.frame function, but not chunk autocomplete.  I've loaded knitr because only loaded libraries can be autocompleted, but this didn't help.

![image](https://github.com/user-attachments/assets/14a5d8ab-851c-435e-8d1e-3c456f16b00e)

Thanks

**Comment by rg-ch** [comment]
Hello again, I can't make it working for rnoweb. 

Do I have to install the R package  languageserver for chunk autocomplete in rnw, because the word="id" as in your screenshot isn't an option in rmd which seems based on the file chunk.lua from comp-r. Are there different sources ? 

I'm already happy with the bugs fixed now, **thanks a lot**. Furthermore, shouldn't you add lsp_signature  to the minimal lua configuration of the  Wiki page because on of its function may be called (has_words_before) .

Thanks ... i will try to find a solution later ..

**Comment by jalvesaq** [comment]
> I don't understand why auto-complete works for data.frame function, but not chunk autocomplete.

It's works on my side, and I get the same completion menu in Quarto and Rmd (including the `id:` field). In the screenshot, I was using your `init.lua`.  I renamed my `~/.config/nvim` directory, created an empty one and put you `init.lua` in it. And, because I can't replicate the bug (even with your `init.lua`), I don't know how to fix it.

I don't use completion from the `rlanguageserver`. I have this on my `~/.Rprofile`:

```r
# Disable completion from the language server
options(languageserver.server_capabilities =
        list(completionProvider = FALSE,
             completionItemResolve = FALSE))
```

**Comment by jalvesaq** [comment]
You could try:

- Delete or rename your `~/.config/nvim` directory.
- Delete the `~/.local/share/nvim/` directory.
- Create an empty `~/.config/nvim` directory and copy your `init.lua` to it.

**Comment by rg-ch** [comment]
Thank your very much for your tips and your explaining that you were able to have a running solution with my init.lua. That's good to know. I tried your strategy twice without improvement. The auto-complete menu doesn't appear.

in rmd with a newly created environment in config and share
i have the following options,there's no "id"  and it seems in cmp-r /chunk.lea there's also no word="id".  

Do we trigger the same source. I only try to understand.   

![image](https://github.com/user-attachments/assets/7ef96945-2b3e-4675-9b5b-28cf99d79f49)

Thank you again but I think I'm helpless.
Best regards

**Comment by jalvesaq** [comment]
I'm sorry, only now I remembered: you have to install Quarto to get completion for fields in `#| ` comments because `cmp-r` gets the data from `yaml-intelligence-resources.json` which is part of Quarto installation.

**Comment by jalvesaq** [comment]
I manually copied the options from https://yihui.org/knitr/options/#chunk-options in April 2021. This data is used for completion in `Rmd` and `Quarto` chunk headers. But the completion of fields in `#|` comments uses data from Quarto installation.

It seems that there are not too many people editing `Rnoweb` files with `R.nvim`. So, you will likely find more bugs. Please, keep reporting them.

**Comment by rg-ch** [comment]
OK, thank you. I'm released that there's an explanation.  I've installed quarto and did a successfully _quarto check_.
and i added  after some error messages following plugins in my init.lua, not knowing really if that's the state of the art.

 { 
"neovim/nvim-lspconfig",
   'quarto-dev/quarto-nvim',
 'jmbuhr/otter.nvim'
 },

and now I have the same options as you.

![image](https://github.com/user-attachments/assets/1093e45f-a3f0-493e-b5a0-63bc62f58b25)

Thank you very much for your help.  Do you think It's better to switch to quarto than to stay with rnoweb. I need to read more about quarto. 
I will keep  reporting errors on rnoweb, but unfortunately my understanding of lua isn't enough and I need a lot of trial and errors.      
Best regards
Roman

**Comment by jalvesaq** [comment]
In my opinion, if you use Rnoweb to write papers for journals that accept LaTeX, and if you are happy with Beamer, then you don't need Quarto. If after writing a paper in Rnoweb you have to convert it to Word, then it's better to use Rmd or Quarto.

Quarto is slower than Rmd, but has a few advantages: https://stackoverflow.com/questions/72089640/what-are-the-benefits-of-using-quarto-over-rmarkdown

I'm not using `quarto-nvim` and `otter.nvim`. They allow you to use the LSP for completion of both R and Python code in Quarto documents.

**Comment by rg-ch** [comment]
Thanks for all the information and your help.
