### ISSUE TITLE
Remove support for Evince, Okular and Qpdfview

### ISSUE THREAD

**Issue by jalvesaq** [R-nvim/R.nvim#32]
I can't see any reason to keep support for Evince, Okular, and qpdfview. They are better than Zathura for annotation, filling forms, etc. But we only need to display the newly generated PDF quickly, and Zathura excels in this task.

So, I propose to delete the files `evince.lua`, `okular.lua`, and `qpdfview.lua`. It will still be possible to use them as "generic" pdf viewers, but without the SyncTeX support.

@PMassicotte ? @she3o ?

**Comment by jalvesaq** [comment]
I can also keep the Lua files but don't use them. So, if someone wanted to implement the SyncTeX support, it would be easier.

**Comment by PMassicotte** [comment]
I will talk for myself, but I only used Zathura. So it is all good with me :)

**Comment by jalvesaq** [comment]
I will disable the other three, but keep their Lua files for at least a couple of weeks after the inauguration of R.nvim. This way, if anybody wants to support them in the future, it will be possible to recover the Lua code.
