### ISSUE TITLE
sending function to the R console

### ISSUE THREAD

**Issue by samtrek** [R-nvim/R.nvim#44]
I dont know if sending function to the R console has been implemented, I am having difficulty in sending functions to the R console, it is always returning error, and the functions do not work. I have tried all the new key combinations none of which is working for now, unless I want to source the whole file, which I have no plan of doing for now, as I have to test the functions make sure they are working.

**Comment by jalvesaq** [comment]
Please, see https://github.com/R-nvim/R.nvim/pull/38

**Comment by samtrek** [comment]
thank you will for the information, will wait for its implementation as stipulated in #38 then
