### ISSUE TITLE
`quarto_intel` not yet implemented.

### ISSUE THREAD

**Issue by wklimowicz** [R-nvim/R.nvim#48]
Not sure if this is already on the backlog, but in case it wasn't the `quarto_intel` option isn't currently implemented, and neovim starts with `Unrecognised option: quarto_intel`.

https://github.com/R-nvim/R.nvim/blob/79db76a753519c36df531ff69e3de7ad3ddc28b8/doc/R.nvim.txt#L697

**Comment by wklimowicz** [comment]
Never mind, looks like it is implemented in [cmp-r](https://github.com/R-nvim/cmp-r). Does the line above need to be deleted since it's set in cmp-r?

**Comment by jalvesaq** [comment]
This option now is in [cmp-r](https://github.com/R-nvim/cmp-r).
