### ISSUE TITLE
set up assign map to mimic ESS behaviour

### ISSUE THREAD

**Issue by maitra** [R-nvim/R.nvim#53]
In ESS, `_` converts to `<-` (the assignment operator) while using `_` in quick succession (i.e. `__`) switches it back to `_`. This is a throwback to the old days (before `R 1.6`) when `_` was allowed as an assignment operator. Is it possible to get this behaviour with `nvim-R`?

**Comment by jalvesaq** [comment]
@maitra, could you try the branch [underscore](https://github.com/R-nvim/R.nvim/tree/underscore)? I believe it does what you want.

**Comment by jalvesaq** [comment]
I compared the default behavior of `Nvim-R` in Vim and `R.nvim` with the option `assign_map = "_"` in Neovim and they seem to be identical. I will merge the changes, but you can reopen the issue if something is wrong.
