### ISSUE TITLE
lots of error out on assigned function call and entering arguments into functions as nvim info (notification)

### ISSUE THREAD

**Issue by samtrek** [R-nvim/R.nvim#65]
Error obtained from calling an assigned function.
Error executing vim.schedule lua callback: /.local/share/nvim/lazy/cmp-r/lua/cmp_r/init.lua:208: attempt to call upvalue 'send_to_nvimcom' (a nil value)
stack traceback:
	.local/share/nvim/lazy/cmp-r/lua/cmp_r/init.lua:208: in function 'resolve'
	...mtrek/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:384: in function 'resolve'
	./.local/share/nvim/lazy/nvim-cmp/lua/cmp/entry.lua:495: in function 'resolve'
	/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:287: in function 'fn'
	.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:71: in function <.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:69>

Error obtained on entering arguments to an assigned function
Error detected while processing TextChangedI Autocommands for "*":

The functions work as they ought to, but the frequent error output can be a sort of "distraction", is there a way in which it can be muted?

**Comment by samtrek** [comment]
seems to be an auto completion issue linked with cmp-r as stated in the issue opened below
https://github.com/R-nvim/cmp-r/issues/1

**Comment by PMassicotte** [comment]
Try using this commit for now:

```lua
    commit = "1356c3f00a07219e6585af4dead4ced6220a84c4",
```

**Comment by PMassicotte** [comment]
Will close it since it is the same as https://github.com/R-nvim/cmp-r/issues/1
