### ISSUE TITLE
:RSend command is broken

### ISSUE THREAD

**Issue by fbearoff** [R-nvim/R.nvim#67]
Trying to execute an :Rsend command produces the following error

``` 
Error  03:43:24 PM msg_show.lua_error   RSend help() Error executing Lua callback: /home/frank/.local/share/nvim/lazy/R.nvim/lua/r/term.lua:25: attempt to concatenate local 'command' (a table value)
stack traceback:
	/home/frank/.local/share/nvim/lazy/R.nvim/lua/r/term.lua:25: in function 'cmd'
	/home/frank/.local/share/nvim/lazy/R.nvim/lua/r/config.lua:733: in function </home/frank/.local/share/nvim/lazy/R.nvim/lua/r/config.lua:733>
```

**Comment by PMassicotte** [comment]
Do you have a precise example? I can not reproduce. I just did

```
:RSend x <- 1
```

and it worked

**Comment by jalvesaq** [comment]
I can't replicate the bug. When I do `:RSend help()` the documentation for "help" (package "utils") is displayed. Please, look at the options `clear_line` and `editing_mode`. Maybe they are being set wrongly in your system.

**Comment by fbearoff** [comment]
That was it! 

Setting `clear_line = true` results in the error

**Comment by jalvesaq** [comment]
Thank you for reporting!

**Comment by jalvesaq** [comment]
You should be able to use the option `clear_line` now. Please, reopen the issue if it's not fixed.
