### ISSUE TITLE
Is RAction still supported?

### ISSUE THREAD

**Issue by jarodmeng** [R-nvim/R.nvim#70]
Back in nvim-R, I used `RAction` extensively to map simple keystrokes to custom functions (e.g. `colnames()`, `show_query()`, etc). It seems that RAction is not supported in R.nvim?

**Comment by jalvesaq** [comment]
I don't have a computer now, but, please, look at the examples at
lua/r/maps.lua.

**Comment by vitallish** [comment]
Thanks for the pointer @jalvesaq .

@jarodmeng  - looks like the new syntax is something like: 

```
require('r.run').action('head')
```

I was able to run the following command:
```
:lua require('r.run').action('head')
```

**Comment by jalvesaq** [comment]
Yes. That's it!

**Comment by jalvesaq** [comment]
The documentation (`doc/R.nvim.txt`) also has examples of how to call the function...

**Comment by jarodmeng** [comment]
Thanks, @vitallish and @jalvesaq . I searched for "RAction" in the documentation and couldn't find any match. It works now!
