### ISSUE TITLE
Unrecognized option "editing_mode"

### ISSUE THREAD

**Issue by fbearoff** [R-nvim/R.nvim#71]
I get the following error message if I set `editing_mode = "vi"` as an option 

`Warn  06:17:26 PM notify.warn R.nvim Unrecognized option 'editing_mode'.`

Lazy.nvim config
```
return {
  "R-nvim/R.nvim",
  lazy = false,
  opts = {
    editing_mode = "vi",
  },
}
```

inputrc
```
set editing-mode vi
set show-mode-in-prompt on
set vi-cmd-mode-string \1\e[2 q\2(c)
set vi-ins-mode-string \1\e[5 q\2(i)

$if R
    set bell-style none
$else
    set bell-style audible
$endif
```

**Comment by jalvesaq** [comment]
Thank you for reporting the bug! I forgot to add the option to the config table, but the bug should be fixed now.
