### ISSUE TITLE
Escaping single quotes when sending to R console

### ISSUE THREAD

**Issue by typhooncamel** [R-nvim/R.nvim#73]
When sending code to the R console (on tmux), all single quotes appear to be escaped and come back with error. There is no problem when there are no single quotes, or when there are double quotes.

For example:
`library(tidyr)` runs fine,
`library("tidyr")` runs fine,
`library('tidyr')` leads to
```
> library('\\''tidyr'\\'')
Error: unexpected string constant in "library('\\''tidyr'"
```

**Comment by jalvesaq** [comment]
Thanks for reporting the bug. Escaping single quotes was required in VimScript, but not in Lua.
