### ISSUE TITLE
`reprex` not working (file  not found)

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#75]
Trying to run this, I get an error:

```r
reprex::reprex({
  plot(1)
}, std_out_err = TRUE)
```

```r
Error in abs_path(input) : 
  The file 'super-sable_reprex.R' does not exist.
In addition: Warning message:
In normalizePath(x, winslash = winslash, mustWork = must_work) :
  path[1]="super-sable_reprex.R": No such file or directory
```

This works fine in `radian` outside `nvim`. My guess it has to do with relative path, but I can not find why at this time.

**Comment by jalvesaq** [comment]
I confirm that it works with `setwd = "no"` (I have `vim.o.autochdir = true` in my `init.lua`). The option was introduced in 2014: https://github.com/jcfaria/Vim-R-plugin/pull/99
Perhaps we should change the default value of `setwd` to "no"...

**Comment by PMassicotte** [comment]
I have it set to "yes". Doing some test , will come back in a few.
