### ISSUE TITLE
MACOS: [Server] Error opening '/opt/homebrew/lib/R/4.3/site-library/00LOCK-commonmark/DESCRIPTION'

### ISSUE THREAD

**Issue by JulianDicken** [R-nvim/R.nvim#81]
Any idea what's causing this ? Have not used Neovim or macOS much so im not sure where to look to fix this :)

**Comment by jalvesaq** [comment]
Please, search "R 00LOCK" on the web. You probably should delete the directory.

**Comment by jalvesaq** [comment]
Anyway, thank you for reporting the issue. I will make `R.nvim` skip the `00LOCK` directory.
