### ISSUE TITLE
R.nvim won't use user tmux configuration

### ISSUE THREAD

**Issue by typhooncamel** [R-nvim/R.nvim#84]
When the R console is started using an external terminal (`external_term = true`), when using `notmuxconf = true`, tmux does not start with the user tmux configuration (in `~/.tmux.conf`). This used to work no problem in Nvim-R when `R_notmuxconf = 1`.

**Comment by jalvesaq** [comment]
I'm sorry. I've forgotten to add `notmuxconf` to the list of options that changed from `Nvim-R` to `R.nvim`. It's done now.

**Comment by typhooncamel** [comment]
Obviously no apologies needed! Just bringing up whatever little issues I may encounter. Thank you for such swift responses and fixes!
