### ISSUE TITLE
Connection with rnvimserver was lost > Error sending message header to R.nvim: -1

### ISSUE THREAD

**Issue by JulianDicken** [R-nvim/R.nvim#86]
Error message above pops up every now and then. Not sure If I can say exactly when and when not, but it is every now and then and will reappear every time I restart nvim until I restart my shell

**Comment by jalvesaq** [comment]
This message is normal only if R is running in an external terminal emulator and you quit Neovim before quitting R. I will change the message to "Connection with R.nvim was lost" because users are not supposed to know what `rnvimserver` is.

**Comment by jalvesaq** [comment]
@JulianDicken, could you please try the branch [move_c_code](https://github.com/R-nvim/R.nvim/tree/move_c_code)?

I moved a lot of code from `rnvimserver.c` to other files. It was just a copying and pasting process that should neither create nor fix bugs, only make the overall code more organized. But when I finished moving the code from one place to another, I ran the `rnvimserver` through Valgrind and found an "invalid read of size 1". Usually, these invalid reads result in a crash at a random later time.

**Comment by jalvesaq** [comment]
I added to the Wiki instructions on how to use Valgrind to debug `R.nvim` : https://github.com/R-nvim/R.nvim/wiki/Debugging-C-code-with-Valgrind

**Comment by JulianDicken** [comment]
Uh sorry I would love to try but I have not used C much before nor am I very comfortable with Lua and nvim. I can *probably* figure this out in a bit but right now I am unfortunately a bit too busy. If you can wait I can try, in due time

**Comment by JulianDicken** [comment]
I have installed the branch you mentioned though and I have not gotten an error message at startup at least and :qa which previously resulted in the issue mentioned above upon restarting nvim seems to work fine now

**Comment by jalvesaq** [comment]
Thanks for the feedback! The changes are merged into the main branch.
