### ISSUE TITLE
Completion stopped working?

### ISSUE THREAD

**Issue by PMassicotte** [R-nvim/R.nvim#94]
Just updated both plugins, and I am not received any code completion in R. Is it only on my side?

**Comment by PMassicotte** [comment]
Reverting to https://github.com/R-nvim/R.nvim/commit/660419773546210f7f6863a7e261375726ff0e61 makes it working again.

**Comment by jalvesaq** [comment]
I confirm the bug... I will see how to fix it without bringing the Valgrind bug back.
