### ISSUE TITLE
readme points to nvim-r instead of R-nvim

### ISSUE THREAD

**Issue by dinga92** [R-nvim/R.nvim#97]
Line 78 in readme.md says: Please read the plugin's [documentation](https://github.com/jamespeapen/Nvim-R/wiki) for instructions on usage. See also the output of `:RMapsDesc`.

Instead of doc/R.nvim.txt or https://github.com/R-nvim/R.nvim/wiki.

**Comment by jalvesaq** [comment]
Thank you for reporting the mistake!
